{
  "dependencyTree": {
    "Abarth": {
      "100": {
        "1998-2004": {
          "Continental Test Variant 1": [
            {
              "fitmentLabel": "185/65 R15",
              "width": 185,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "105V"
            }
          ]
        }
      },
      "100 Avant": {},
      "100 NX": {},
      "100 Quattro": {},
      "1007": {},
      "106": {},
      "106 Elektrisch": {},
      "106 Rallye": {},
      "106 S16": {},
      "106 XSi": {},
      "107": {},
      "108": {},
      "111": {},
      "114": {},
      "115": {},
      "121": {},
      "124 GT": {},
      "124 Spider": {},
      "145": {},
      "146": {},
      "147": {},
      "147 GTA": {},
      "155": {},
      "155 Q4": {},
      "156": {},
      "156 Crosswagon Q4": {},
      "156 GTA": {},
      "156 Q System": {},
      "156 Sportwagon": {},
      "156 Sportwagon GTA": {},
      "156 Sportwagon Q System": {},
      "159": {},
      "159 Q4": {},
      "159 Sportwagon": {},
      "159 Sportwagon Q4": {},
      "160": {},
      "164": {},
      "164 Q4": {},
      "165": {},
      "166": {},
      "175 CSR": {},
      "190": {},
      "190 E": {},
      "190 Evolution II": {},
      "1er Cabrio": {},
      "220 Coup\u00e9": {
        "2005-2010": {
          "Continental Test Variant 11": [
            {
              "fitmentLabel": "245/45 R19",
              "width": 245,
              "aspectRatio": 45,
              "diameter": 19,
              "speedLoadIndex": "98V"
            }
          ]
        }
      }
    },
    "Aixam": {
      "1er Coup\u00e9": {},
      "1er Limousine": {},
      "1er M": {},
      "2": {},
      "2 Hybride": {},
      "200 CSR": {},
      "200 D": {},
      "200 E": {},
      "200 Kombi": {},
      "200 Quattro": {},
      "200 SX (S13)": {},
      "200 SX (S14)": {},
      "200 Vitesse": {},
      "2008": {},
      "2008 Crossway": {},
      "2008 II": {},
      "205": {},
      "205 Cabrio": {},
      "205 GT": {},
      "205 GTI": {},
      "205 Gentry": {},
      "205 Rallye": {},
      "205 van": {},
      "206": {},
      "206 +": {},
      "206 CC": {},
      "206 GT": {},
      "206 RC": {},
      "206 S16": {},
      "206 SW": {},
      "206 SW S16": {},
      "206 Sedan": {},
      "207": {},
      "207 +": {},
      "207 CC": {},
      "207 RC": {},
      "207 SW": {},
      "207 SW Outdoor": {},
      "207 SW RC": {},
      "208": {},
      "208 GT4": {},
      "208 GTB Turbo": {},
      "208 GTI": {},
      "208 GTI 30th": {},
      "208 GTS Turbo": {},
      "100 Avant": {
        "2005-2010": {
          "Continental Test Variant 2": [
            {
              "fitmentLabel": "185/65 R15",
              "width": 185,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      },
      "220 GSI Coup\u00e9": {
        "2011-2016": {
          "Continental Test Variant 12": [
            {
              "fitmentLabel": "185/65 R15",
              "width": 185,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "105V"
            }
          ]
        }
      }
    },
    "Alfa Romeo": {
      "208 II": {},
      "213": {},
      "214": {},
      "214 Cabrio": {},
      "214 GSI": {},
      "214 IS": {},
      "214 ISL": {},
      "215 Cabrio": {},
      "216 Cabrio": {},
      "216 Coup\u00e9": {},
      "216 GSI": {},
      "216 GTI": {},
      "216 SI": {},
      "216 SLI": {},
      "218": {},
      "220": {},
      "220 Coup\u00e9": {},
      "220 GSI Coup\u00e9": {},
      "220 GTI": {
        "2017-2021": {
          "Continental Test Variant 1": [
            {
              "fitmentLabel": "185/65 R15",
              "width": 185,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      },
      "220 Kombi": {},
      "220 SD": {},
      "220 SDI": {},
      "220 SLI": {},
      "222": {},
      "222 4V": {},
      "224 V": {},
      "230 Coup\u00e9": {},
      "230 E": {},
      "238": {},
      "240": {},
      "240 Kombi": {},
      "25": {},
      "250": {},
      "25S15": {},
      "25S18": {},
      "260 E": {},
      "260 E 4Matic": {},
      "260 SE": {},
      "275 S3": {},
      "280": {},
      "280 Kombi": {},
      "288 GTO": {},
      "296 GTB": {},
      "29L10": {},
      "29L11": {},
      "100 NX": {
        "2011-2016": {
          "Continental Test Variant 3": [
            {
              "fitmentLabel": "185/65 R15",
              "width": 185,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "96H"
            }
          ]
        }
      }
    },
    "Alpina": {
      "29L12": {},
      "29L13": {},
      "29L14": {},
      "29L15": {},
      "2er Active Tourer": {},
      "2er Cabrio": {},
      "2er Coup\u00e9": {},
      "2er Gran Coup\u00e9": {},
      "2er Gran Tourer": {},
      "3": {},
      "3 Limousine": {},
      "3 MPS": {},
      "3 Wheeler": {},
      "3-Eleven 430": {},
      "3-Eleven Race": {},
      "3-Eleven Road": {},
      "300": {},
      "300 4Matic": {},
      "300 4Matic Kombi": {},
      "300 Cabrio": {},
      "300 Kombi": {},
      "300 ZX (Z32)": {},
      "3000 GT Coup\u00e9": {},
      "3008": {},
      "3008 Crossway": {},
      "3008 Grip Control": {},
      "3008 Hybrid4": {},
      "3008 II": {},
      "300C": {},
      "300C AWD": {},
      "300C SRT8": {},
      "300C SRT8 Touring": {},
      "300C Touring": {},
      "300M": {},
      "300S": {},
      "306": {},
      "306 Cabrio": {},
      "306 Kombi": {},
      "306 S16": {},
      "306 XSI": {},
      "307": {},
      "307 CC": {},
      "307 SW": {},
      "308": {},
      "308 CC": {},
      "100 Quattro": {
        "2017-2021": {
          "Continental Test Variant 4": [
            {
              "fitmentLabel": "185/65 R15",
              "width": 185,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "98V"
            }
          ]
        }
      },
      "220 Kombi": {
        "2022-2026": {
          "Continental Test Variant 2": [
            {
              "fitmentLabel": "185/65 R15",
              "width": 185,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "96H"
            }
          ]
        }
      }
    },
    "Alpine": {
      "308 GT4": {},
      "308 GTB": {},
      "308 GTBi": {},
      "308 GTS": {},
      "308 GTS Quattrovalvole": {},
      "308 GTSi": {},
      "308 GTi": {},
      "308 II": {},
      "308 II GT": {},
      "308 II GTi": {},
      "308 II SW": {},
      "308 II SW GT": {},
      "308 III": {},
      "308 III SW": {},
      "308 SW": {},
      "309": {},
      "309 Automatik": {},
      "309 GTI": {},
      "309 GTI 16S": {},
      "320 Coup\u00e9": {},
      "320 E": {},
      "320 Kombi": {},
      "320 SEL": {},
      "320 SEL Mill Migh": {},
      "3200 GT": {},
      "323 F": {},
      "323 IV": {},
      "323 IV 4WD": {},
      "323 IV GT-R": {},
      "323 IV Kombi": {},
      "323 V": {},
      "323 VI": {},
      "328 GTB": {},
      "328 GTS": {},
      "33": {},
      "33 4X4": {},
      "33 GTA": {},
      "33 Q4": {},
      "33 Sportwagon": {},
      "33 Sportwagon 4X4": {},
      "33S11V": {},
      "33S13V": {},
      "33S15V": {},
      "348 GTB": {},
      "348 GTS": {},
      "1007": {
        "2022-2026": {
          "Continental Test Variant 5": [
            {
              "fitmentLabel": "195/55 R16",
              "width": 195,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      },
      "220 SD": {
        "1998-2004": {
          "Continental Test Variant 3": [
            {
              "fitmentLabel": "185/65 R15",
              "width": 185,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "98V"
            }
          ]
        }
      }
    },
    "Artega": {
      "348 Spider": {},
      "348 TB": {},
      "350Z Coup\u00e9": {},
      "350Z Roadster": {},
      "35C10": {},
      "35C11": {},
      "35C11V": {},
      "35C12": {},
      "35C13": {},
      "35C13V": {},
      "35C14": {},
      "35C14G": {},
      "35C14N": {},
      "35C14V": {},
      "35C15": {},
      "35C15L": {},
      "35C15V": {},
      "35C16V": {},
      "35C17": {},
      "35C17L": {},
      "35C17V": {},
      "35C18": {},
      "35C18V": {},
      "35C21": {},
      "35C21V": {},
      "35S10": {},
      "35S11": {},
      "35S11V": {},
      "35S12": {},
      "35S13": {},
      "35S13V": {},
      "35S14": {},
      "35S14G": {},
      "35S14N": {},
      "35S14V": {},
      "35S15": {},
      "35S15V": {},
      "35S16V": {},
      "35S17": {},
      "35S17V": {},
      "35S18": {},
      "35S18V": {},
      "35S21": {},
      "35S21V": {},
      "360": {},
      "106": {
        "1998-2004": {
          "Continental Test Variant 6": [
            {
              "fitmentLabel": "195/55 R16",
              "width": 195,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "91V"
            }
          ]
        }
      },
      "220 SDI": {
        "2005-2010": {
          "Continental Test Variant 4": [
            {
              "fitmentLabel": "195/55 R16",
              "width": 195,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      }
    },
    "Aston Martin": {
      "360 Challenge Stradale": {},
      "360 Modena": {},
      "360 Modena F1": {},
      "360 Spider": {},
      "360 Spider F1": {},
      "370Z": {},
      "370Z Nismo": {},
      "370Z Roadster": {},
      "3er ActiveHybrid 3": {},
      "3er Cabrio": {},
      "3er Compact": {},
      "3er Coup\u00e9": {},
      "3er Limousine": {},
      "3er Limousine GT": {},
      "3er Touring": {},
      "4.24V": {},
      "400": {},
      "400 E": {},
      "4007": {},
      "4008": {},
      "405": {},
      "405 4X4": {},
      "405 Kombi": {},
      "405 Kombi 4X4": {},
      "405 MI16": {},
      "405 MI16 4X4": {},
      "405 T16": {},
      "406": {},
      "406 Coup\u00e9": {},
      "406 Kombi": {},
      "407": {},
      "407 SW": {},
      "412": {},
      "414": {},
      "416": {},
      "416 Tourer": {},
      "418": {},
      "418 Tourer": {},
      "420": {},
      "420 SE": {},
      "420 Tourer": {},
      "4200 GT": {},
      "430": {},
      "440": {},
      "45": {},
      "106 Elektrisch": {
        "2005-2010": {
          "Continental Test Variant 7": [
            {
              "fitmentLabel": "195/55 R16",
              "width": 195,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "94W"
            }
          ]
        }
      },
      "220 SLI": {
        "2011-2016": {
          "Continental Test Variant 5": [
            {
              "fitmentLabel": "195/55 R16",
              "width": 195,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "91V"
            }
          ]
        }
      }
    },
    "Audi": {
      "45 Automatik": {},
      "456 GT": {},
      "456 GTA": {},
      "456 M GT": {},
      "456 M GTA": {},
      "458 Italia": {},
      "458 Italia Spider": {},
      "458 Speciale": {},
      "458 Speciale A": {},
      "460": {},
      "480": {},
      "480 Turbo": {},
      "485 CSR": {},
      "485 S3": {},
      "488 GTB": {},
      "488 Pista": {},
      "488 Pista Spider": {},
      "488 Spider": {},
      "4C": {},
      "4C Spider": {},
      "4er Cabrio": {},
      "4er Cabriolet": {},
      "4er Coup\u00e9": {},
      "4er Gran Coup\u00e9": {},
      "5": {},
      "500": {},
      "500 Abarth": {},
      "500 C": {},
      "500 C Abarth": {},
      "500 C Esseesse": {},
      "500 Cabrio Italia": {},
      "500 E": {},
      "500 Esseesse": {},
      "500 L": {},
      "500 SE": {},
      "500 SL": {},
      "500 SL Cabrio": {},
      "500 X": {},
      "500 X 4X4": {},
      "500-4": {},
      "500-5": {},
      "500-5 Pick-Up": {},
      "5008": {},
      "5008 II": {},
      "500e": {},
      "106 Rallye": {
        "2011-2016": {
          "Continental Test Variant 8": [
            {
              "fitmentLabel": "195/55 R16",
              "width": 195,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      },
      "222": {
        "2017-2021": {
          "Continental Test Variant 6": [
            {
              "fitmentLabel": "195/55 R16",
              "width": 195,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "94W"
            }
          ]
        }
      }
    },
    "Austin": {
      "504": {},
      "504 Kombi": {},
      "505 GTI": {},
      "505 Kombi": {},
      "505 Turbo Injection": {},
      "508": {},
      "508 Hybrid4": {},
      "508 II": {},
      "508 II SW": {},
      "508 RXH": {},
      "508 SW": {},
      "50C14G": {},
      "50C14N": {},
      "50C15": {},
      "50C15H": {},
      "50C15V": {},
      "50C17": {},
      "50C17H": {},
      "50C17V": {},
      "50C18": {},
      "50C21": {},
      "50C21V": {},
      "512 TR": {},
      "540C Coup\u00e9": {},
      "550 Barchetta Pininfarina": {},
      "550 Maranello": {},
      "550 Maranello Evolution": {},
      "570GT Coup\u00e9": {},
      "570S Coup\u00e9": {},
      "570S Spider": {},
      "575 M Marenello": {},
      "575 M Marenello F1": {},
      "575 Superamerica": {},
      "595": {},
      "595 C Competizione": {},
      "595 C Turismo": {},
      "595 Competizione": {},
      "595 Pista": {},
      "595 Turismo": {},
      "599 GTB": {},
      "599 GTB Fiorano": {},
      "599 GTO": {},
      "599 SA Aperta": {},
      "5er ActiveHybrid 5": {},
      "5er Limousine": {},
      "106 S16": {
        "2017-2021": {
          "Continental Test Variant 9": [
            {
              "fitmentLabel": "195/65 R15",
              "width": 195,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "91H"
            }
          ]
        }
      },
      "222 4V": {
        "2022-2026": {
          "Continental Test Variant 7": [
            {
              "fitmentLabel": "195/55 R16",
              "width": 195,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      }
    },
    "Bentley": {
      "5er Limousine GT": {},
      "5er Touring": {},
      "6": {},
      "6 Kombi": {},
      "6 Kombi (AWD)": {},
      "6 MPS": {},
      "6 Wagon": {},
      "6 Wagon AWD": {},
      "600 SE": {},
      "600 SL": {},
      "600LT Coup\u00e9": {},
      "600LT Spider": {},
      "601": {},
      "605": {},
      "605 SV 24": {},
      "607": {},
      "612 Scaglietti": {},
      "618 SI": {},
      "620 GSI": {},
      "620 I": {},
      "620 SDI": {},
      "620 SI": {},
      "620 SLI": {},
      "620 Turbo": {},
      "620R": {},
      "620S": {},
      "623 GSI": {},
      "623 SI": {},
      "623 SLI": {},
      "626": {},
      "626 4WS": {},
      "626 GF": {},
      "626 GF Kombi": {},
      "626 Kombi": {},
      "650S Can-Am": {},
      "650S Coup\u00e9": {},
      "650S Spider": {},
      "65C14G": {},
      "65C14N": {},
      "65C15": {},
      "65C15H": {},
      "65C17H": {},
      "65C18": {},
      "675LT": {},
      "675LT Spider": {},
      "106 XSi": {
        "2022-2026": {
          "Continental Test Variant 10": [
            {
              "fitmentLabel": "195/65 R15",
              "width": 195,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "94V"
            }
          ]
        }
      },
      "224 V": {
        "1998-2004": {
          "Continental Test Variant 8": [
            {
              "fitmentLabel": "195/65 R15",
              "width": 195,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "91H"
            }
          ]
        }
      }
    },
    "Bertone": {
      "695 Biposto": {},
      "695 SS Assetto Corsa": {},
      "695 Tributo Ferrari": {},
      "6er Cabrio": {},
      "6er Coup\u00e9": {},
      "6er Gran Coup\u00e9": {},
      "6er Gran Turismo": {},
      "7 MPV": {},
      "7 SUV": {},
      "700 Biturbo": {},
      "70C14G": {},
      "70C15H": {},
      "70C17H": {},
      "70C18": {},
      "720S": {},
      "720S Spider": {},
      "740": {},
      "740 Kombi": {},
      "75": {},
      "75 Automatik": {},
      "75 Kombi": {},
      "75 Kombi Automatik": {},
      "760": {},
      "760 Kombi": {},
      "780": {},
      "7er ActiveHybrid 7": {},
      "7er ActiveHybrid 7 L": {},
      "7er Limousine": {},
      "80": {},
      "80 Avant": {},
      "80 Avant Quattro": {},
      "80 Quattro": {},
      "800 Rocket": {},
      "800 ibusiness": {},
      "806": {},
      "807": {},
      "812 Superfast": {},
      "820": {},
      "820 IE": {},
      "820 IS": {},
      "820 ISE": {},
      "820 ISL": {},
      "820 Vitesse": {},
      "825": {},
      "825 SD": {},
      "107": {
        "1998-2004": {
          "Continental Test Variant 11": [
            {
              "fitmentLabel": "195/65 R15",
              "width": 195,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "98V"
            }
          ]
        }
      },
      "230 Coup\u00e9": {
        "2005-2010": {
          "Continental Test Variant 9": [
            {
              "fitmentLabel": "195/65 R15",
              "width": 195,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "94V"
            }
          ]
        }
      }
    },
    "Bmw": {
      "825 SLD": {},
      "827": {},
      "827 Coup\u00e9": {},
      "827 ISL": {},
      "827 Sterling": {},
      "827 Vitesse": {},
      "850": {},
      "850 Kombi": {},
      "8C Competizione": {},
      "8C Competizione Spider": {},
      "8er Cabrio": {},
      "8er Coup\u00e9": {},
      "9-3": {},
      "9-3 Cabrio": {},
      "9-3 Coup\u00e9": {},
      "9-3 Sport-Hatch": {},
      "9-3 Sport-Hatch XWD": {},
      "9-3 XWD": {},
      "9-4X": {},
      "9-5": {},
      "9-5 (XWD)": {},
      "9-5 Estate": {},
      "90": {},
      "90 Quattro": {},
      "900": {},
      "900 Coup\u00e9": {},
      "9000": {},
      "9000 Cabrio": {},
      "911 Carrera": {},
      "911 Carrera - 40 Jahre 911": {},
      "911 Carrera 4": {},
      "911 Carrera 4 - 40 Jahre 911": {},
      "911 Carrera 4 Cabrio": {},
      "911 Carrera 4 GTS": {},
      "911 Carrera 4 GTS Cabrio": {},
      "911 Carrera 4 S": {},
      "911 Carrera 4 S Cabrio": {},
      "911 Carrera 4 Targa": {},
      "911 Carrera 4 Turbolook": {},
      "911 Carrera 4S": {},
      "911 Carrera 4S Cabrio": {},
      "911 Carrera Cabrio": {},
      "911 Carrera Cabrio - 40 Jahre 911": {},
      "911 Carrera GTS": {},
      "911 Carrera GTS Cabrio": {},
      "108": {
        "2005-2010": {
          "Continental Test Variant 12": [
            {
              "fitmentLabel": "195/65 R15",
              "width": 195,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      },
      "230 E": {
        "2011-2016": {
          "Continental Test Variant 10": [
            {
              "fitmentLabel": "195/65 R15",
              "width": 195,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "98V"
            }
          ]
        }
      }
    },
    "Borgward": {
      "911 Carrera RS": {},
      "911 Carrera S": {},
      "911 Carrera S Cabrio": {},
      "911 Carrera T": {},
      "911 Carrera Targa": {},
      "911 Carrera Targa 4": {},
      "911 Carrera Targa 4 S": {},
      "911 GT1": {},
      "911 GT2": {},
      "911 GT2 RS": {},
      "911 GT3": {},
      "911 GT3 RS": {},
      "911 GT3 RS 4.0": {},
      "911 GT3 Touring": {},
      "911 R": {},
      "911 Speedster": {},
      "911 Targa": {},
      "911 Targa 4": {},
      "911 Targa 4 GTS": {},
      "911 Targa 4S": {},
      "911 Targa 4S GTS": {},
      "911 Turbo": {},
      "911 Turbo Cabrio": {},
      "911 Turbo S": {},
      "911 Turbo S Cabrio": {},
      "918 Spyder": {},
      "924 Carrera GT": {},
      "924 S": {},
      "924 Turbo": {},
      "928 GT": {},
      "928 GTS": {},
      "928 S": {},
      "928 S4": {},
      "929": {},
      "940": {},
      "940 Kombi": {},
      "944": {},
      "944 S": {},
      "944 S2": {},
      "944 S2 Cabrio": {},
      "944 Turbo": {},
      "944 Turbo Cabrio": {},
      "945": {},
      "960": {},
      "960 Kombi": {},
      "111": {
        "2011-2016": {
          "Continental Test Variant 1": [
            {
              "fitmentLabel": "205/50 R17",
              "width": 205,
              "aspectRatio": 50,
              "diameter": 17,
              "speedLoadIndex": "91H"
            }
          ]
        }
      },
      "238": {
        "2017-2021": {
          "Continental Test Variant 11": [
            {
              "fitmentLabel": "195/65 R15",
              "width": 195,
              "aspectRatio": 65,
              "diameter": 15,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      }
    },
    "Brabus": {
      "968": {},
      "968 Cabrio": {},
      "968 Turbo S": {},
      "A 140": {},
      "A 150": {},
      "A 160": {},
      "A 160 CDI": {},
      "A 160 D": {},
      "A 170": {},
      "A 170 CDI": {},
      "A 180": {},
      "A 180 CDI": {},
      "A 180 D": {},
      "A 190": {},
      "A 200": {},
      "A 200 CDI": {},
      "A 200 CDI 4Matic": {},
      "A 200 D": {},
      "A 200 Turbo": {},
      "A 21": {},
      "A 210 Evolution": {},
      "A 220 4Matic": {},
      "A 220 CDI": {},
      "A 220 CDI 4Matic": {},
      "A 220 D": {},
      "A 220 D 4Matic": {},
      "A 250": {},
      "A 250 4Matic": {},
      "A 250 Sport": {},
      "A 250 Sport 4Matic": {},
      "A 250 e": {},
      "A 35": {},
      "A 45 4MATIC": {},
      "A 45 A 4Matic": {},
      "A 45 S": {},
      "A 721": {},
      "A 741": {},
      "A 751": {},
      "A 751 Crossline": {},
      "A 751 Scouty": {},
      "A 751 Sport": {},
      "A1": {},
      "A1 City Carver": {},
      "A1 Quattro": {},
      "A1 Sportback": {},
      "114": {
        "2017-2021": {
          "Continental Test Variant 2": [
            {
              "fitmentLabel": "205/50 R17",
              "width": 205,
              "aspectRatio": 50,
              "diameter": 17,
              "speedLoadIndex": "91V"
            }
          ]
        }
      },
      "240": {
        "2022-2026": {
          "Continental Test Variant 12": [
            {
              "fitmentLabel": "205/50 R17",
              "width": 205,
              "aspectRatio": 50,
              "diameter": 17,
              "speedLoadIndex": "91H"
            }
          ]
        }
      }
    },
    "Bugatti": {
      "A110": {},
      "A110 S": {},
      "A2": {},
      "A3": {},
      "A3 Cabrio": {},
      "A3 Cabrio Quattro": {},
      "A3 Limousine": {},
      "A3 Limousine 30 TDI": {},
      "A3 Limousine 35 TDI": {},
      "A3 Limousine 35 TFSI": {},
      "A3 Limousine 40 TDI quattro": {},
      "A3 Limousine 40 TFSI Quattro": {},
      "A3 Limousine Quattro": {},
      "A3 Quattro": {},
      "A3 Sportback": {},
      "A3 Sportback 30 TDI": {},
      "A3 Sportback 35 TDI": {},
      "A3 Sportback 35 TFSI": {},
      "A3 Sportback 40 TDI quattro": {},
      "A3 Sportback 40 TFSI Quattro": {},
      "A3 Sportback 40 TFSI e": {},
      "A3 Sportback 45 TFSI e": {},
      "A3 Sportback Quattro": {},
      "A3 Sportback e-tron": {},
      "A3 Sportback g-tron": {},
      "A4": {},
      "A4 Allroad": {},
      "A4 Allroad Quattro": {},
      "A4 Avant": {},
      "A4 Avant G-Tron": {},
      "A4 Avant Quattro": {},
      "A4 Cabrio": {},
      "A4 Cabrio Quattro": {},
      "A4 Quattro": {},
      "A5": {},
      "A5 Cabrio": {},
      "A5 Cabrio Quattro": {},
      "A5 Quattro": {},
      "A5 Sportback": {},
      "A5 Sportback G-tron": {},
      "A5 Sportback Quattro": {},
      "A6": {},
      "A6 Allroad Quattro": {},
      "A6 Avant": {},
      "A6 Avant Quattro": {},
      "115": {
        "2022-2026": {
          "Continental Test Variant 3": [
            {
              "fitmentLabel": "205/50 R17",
              "width": 205,
              "aspectRatio": 50,
              "diameter": 17,
              "speedLoadIndex": "94W"
            }
          ]
        }
      },
      "240 Kombi": {
        "1998-2004": {
          "Continental Test Variant 1": [
            {
              "fitmentLabel": "205/50 R17",
              "width": 205,
              "aspectRatio": 50,
              "diameter": 17,
              "speedLoadIndex": "91V"
            }
          ]
        }
      }
    },
    "Buick": {
      "A6 Hybrid": {},
      "A6 Quattro": {},
      "A7 Sportback": {},
      "A7 Sportback Quattro": {},
      "A7 Sportback Quattro Competition": {},
      "A8": {},
      "A8 Hybrid": {},
      "A8 L": {},
      "A8 L Quattro": {},
      "A8 L W12": {},
      "A8 Quattro": {},
      "APE Calessino": {},
      "APE Calessino 200": {},
      "APE Classic": {},
      "APE TM": {},
      "ASX 2WD": {},
      "ASX 4WD": {},
      "ATS": {},
      "ATS Coup\u00e9": {},
      "ATS-V": {},
      "ATS-V Coup\u00e9": {},
      "Acadiane": {},
      "Accent": {},
      "Accord": {},
      "Accord 4WD": {},
      "Accord Coup\u00e9": {},
      "Accord Tourer": {},
      "Accord Type R": {},
      "Accord Type S": {},
      "Accord Type S Tourer": {},
      "Across": {},
      "Actyon": {},
      "Actyon Sports": {},
      "Actyon Sports 4x4": {},
      "Adam": {},
      "Adam S": {},
      "Aero 8": {},
      "Aeromax": {},
      "Aerostar": {},
      "Agera": {},
      "Agera R": {},
      "Agera RS": {},
      "Agera S": {},
      "Agila": {},
      "Alaskan": {},
      "121": {
        "1998-2004": {
          "Continental Test Variant 4": [
            {
              "fitmentLabel": "205/50 R17",
              "width": 205,
              "aspectRatio": 50,
              "diameter": 17,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      },
      "25": {
        "2005-2010": {
          "Continental Test Variant 2": [
            {
              "fitmentLabel": "205/50 R17",
              "width": 205,
              "aspectRatio": 50,
              "diameter": 17,
              "speedLoadIndex": "94W"
            }
          ]
        }
      }
    },
    "Cadillac": {
      "Alaskan 4x4": {},
      "Albea": {},
      "Alfa GT": {},
      "Alhambra": {},
      "Alhambra 4Drive": {},
      "Alhambra 4X4": {},
      "Alhambra AWD": {},
      "Allante": {},
      "Allroad": {},
      "Almera": {},
      "Almera GTI": {},
      "Almera II": {},
      "Almera Tino": {},
      "Alpine A610": {},
      "Alpine GTA V6 GT": {},
      "Alpine GTA V6 Turbo": {},
      "Alpine V6 Le Mans": {},
      "Altea": {},
      "Altea Freetrack": {},
      "Altea Freetrack 4WD": {},
      "Altea XL": {},
      "Alto": {},
      "Amarok": {},
      "Amarok 4Motion": {},
      "Ampera": {},
      "Ampera-e": {},
      "Antara (4x2)": {},
      "Antara (4x4)": {},
      "Apollo": {},
      "Apollo S": {},
      "Applause": {},
      "Applause 4WD": {},
      "Arnage": {},
      "Arnage R": {},
      "Arnage T": {},
      "Arona": {},
      "Arosa": {},
      "Artega GT": {},
      "Artega SE": {},
      "Arteon": {},
      "Arteon 4Motion": {},
      "Artura Coup\u00e9": {},
      "Ascender": {},
      "Ascent": {},
      "Astra F": {},
      "124 GT": {
        "2005-2010": {
          "Continental Test Variant 5": [
            {
              "fitmentLabel": "205/55 R16",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      },
      "250": {
        "2011-2016": {
          "Continental Test Variant 3": [
            {
              "fitmentLabel": "205/50 R17",
              "width": 205,
              "aspectRatio": 50,
              "diameter": 17,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      }
    },
    "Caterham": {
      "Astra F Cabrio": {},
      "Astra F GSI": {},
      "Astra F GT": {},
      "Astra F Kombi": {},
      "Astra F Kombi GSI": {},
      "Astra G": {},
      "Astra G Cabrio": {},
      "Astra G Coup\u00e9": {},
      "Astra G Kombi": {},
      "Astra G OPC": {},
      "Astra G OPC Kombi": {},
      "Astra H": {},
      "Astra H GTC": {},
      "Astra H Kombi": {},
      "Astra H OPC": {},
      "Astra H Twintop": {},
      "Astra J": {},
      "Astra J GTC": {},
      "Astra J GTC OPC": {},
      "Astra J Notchback (Sedan)": {},
      "Astra J OPC": {},
      "Astra J Sports Tourer": {},
      "Astra K": {},
      "Astra K Sedan": {},
      "Astra K Sports Tourer": {},
      "Astra L": {},
      "Ateca": {},
      "Ateca 4drive": {},
      "Atos": {},
      "Atos Prime": {},
      "Auris": {},
      "Auris Hybrid": {},
      "Auris II": {},
      "Auris II Hybrid": {},
      "Auris II Touring Sports": {},
      "Auris II Touring Sports Hybrid": {},
      "Avantime": {},
      "Avensis": {},
      "Avensis Kombi": {},
      "Avensis Verso": {},
      "Aventador": {},
      "Aventador Roadster": {},
      "Aventador S": {},
      "Aventador S Roadster": {},
      "Aventador SVJ": {},
      "124 Spider": {
        "2011-2016": {
          "Continental Test Variant 6": [
            {
              "fitmentLabel": "205/55 R16",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "105V"
            }
          ]
        }
      },
      "25S15": {
        "2017-2021": {
          "Continental Test Variant 4": [
            {
              "fitmentLabel": "205/55 R16",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      }
    },
    "Chevrolet": {
      "Aventador SVJ Roadster": {},
      "Aveo": {},
      "Aviator": {},
      "Aviator (2WD)": {},
      "Ax": {},
      "Ax 4X4": {},
      "Ax Elektrisch": {},
      "Ax GT": {},
      "Ax GTI": {},
      "Ax Sport": {},
      "Aygo": {},
      "Aygo II": {},
      "Aygo X": {},
      "Azure": {},
      "Azure Mulliner": {},
      "Azure T": {},
      "B 10 (E34)": {},
      "B 10 (E39)": {},
      "B 10 4X4": {},
      "B 10 4X4 Touring": {},
      "B 10 Touring (E34)": {},
      "B 10 Touring (E39)": {},
      "B 11": {},
      "B 12 (E32)": {},
      "B 12 (E38)": {},
      "B 12 Coup\u00e9 (E31)": {},
      "B 150": {},
      "B 160": {},
      "B 160 CDI": {},
      "B 160 D": {},
      "B 170": {},
      "B 180": {},
      "B 180 CDI": {},
      "B 180 D": {},
      "B 200": {},
      "B 200 CDI": {},
      "B 200 CDI 4Matic": {},
      "B 200 Natural Gas Drive": {},
      "B 200 Turbo": {},
      "B 200 d": {},
      "B 220 4Matic": {},
      "B 220 CDI": {},
      "B 220 CDI 4Matic": {},
      "B 220 d": {},
      "B 220 d 4Matic": {},
      "145": {
        "2017-2021": {
          "Continental Test Variant 7": [
            {
              "fitmentLabel": "205/55 R16",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "91V"
            }
          ]
        }
      },
      "25S18": {
        "2022-2026": {
          "Continental Test Variant 5": [
            {
              "fitmentLabel": "205/55 R16",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "105V"
            }
          ]
        }
      }
    },
    "Chrysler": {
      "B 250": {},
      "B 250 4Matic": {},
      "B 250 e": {},
      "B 3 (E36)": {},
      "B 3 (E46)": {},
      "B 3 (F30)": {},
      "B 3 Biturbo (E92)": {},
      "B 3 Cabrio (E30)": {},
      "B 3 Cabrio (E36)": {},
      "B 3 Coup\u00e9 (E36)": {},
      "B 3 Coup\u00e9 (E46)": {},
      "B 3 S": {},
      "B 3 S Biturbo (E92)": {},
      "B 3 S Biturbo (F30)": {},
      "B 3 S Biturbo (F30) Allrad": {},
      "B 3 S Biturbo Touring (F31)": {},
      "B 3 S Biturbo Touring (F31) Allrad": {},
      "B 3 S Cabrio": {},
      "B 3 S Coup\u00e9": {},
      "B 3 S Touring": {},
      "B 3 Touring (E30)": {},
      "B 3 Touring (E36)": {},
      "B 3 Touring (E46)": {},
      "B 3 Touring (F31)": {},
      "B 4 S Biturbo Cabrio (F30)": {},
      "B 4 S Biturbo Coup\u00e9 (F30)": {},
      "B 4 S Biturbo Coup\u00e9 (F30) Allrad": {},
      "B 5 Biturbo (F10)": {},
      "B 5 Biturbo (G30)": {},
      "B 5 Biturbo Touring (G31)": {},
      "B 5 S (E60)": {},
      "B 5 Touring Biturbo (F10)": {},
      "B 6": {},
      "B 6 Biturbo": {},
      "B 6 Biturbo Cabrio": {},
      "B 6 Biturbo Coup\u00e9": {},
      "B 6 S Cabrio": {},
      "B 7 (E65)": {},
      "B 7 Coup\u00e9 (E24)": {},
      "B 8 (E36)": {},
      "B 8 Cabrio (E36)": {},
      "B 8 Coup\u00e9 (E36)": {},
      "B 8 Touring (E36)": {},
      "B Elektrisch Drive": {},
      "B-Max": {},
      "146": {
        "2022-2026": {
          "Continental Test Variant 8": [
            {
              "fitmentLabel": "205/55 R16",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      },
      "260 E": {
        "1998-2004": {
          "Continental Test Variant 6": [
            {
              "fitmentLabel": "205/55 R16",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "91V"
            }
          ]
        }
      }
    },
    "Citroen": {
      "B1": {},
      "B14 Post": {},
      "B14 Work": {},
      "B2": {},
      "B63 620": {},
      "B7 Biturbo (F01/F02)": {},
      "B7 Biturbo (G12)": {},
      "B8 Gran Coup\u00e9": {},
      "B9 Tribeca": {},
      "BLS": {},
      "BLS Kombi": {},
      "BRZ": {},
      "BRZ Limited": {},
      "BRZ Limited (AT)": {},
      "BRZ Premium": {},
      "BT-50": {},
      "BX5": {},
      "BX7": {},
      "Baleno": {},
      "Baleno 4WD": {},
      "Baleno GT": {},
      "Baleno Kombi": {},
      "Barchetta": {},
      "Bayon": {},
      "Beetle": {},
      "Beetle Cabrio": {},
      "Bentayga": {},
      "Bentayga Speed": {},
      "Beretta": {},
      "Beretta GTZ": {},
      "Berlingo": {},
      "Berlingo 4x4 Dangel": {},
      "Berlingo Elektrisch": {},
      "Berlingo II": {},
      "Berlingo II V.U": {},
      "Berlingo II V.U 625kg": {},
      "Berlingo II V.U 625kg Baustelle": {},
      "Berlingo II V.U 750kg": {},
      "Berlingo II V.U 750kg Baustelle": {},
      "Berlingo II V.U 800kg Baustelle": {},
      "Berlingo II V.U 850kg": {},
      "Berlingo II V.U Elektrisch": {},
      "Berlingo II XTR": {},
      "Berlingo III Multispace": {},
      "Berlingo III Van": {},
      "147": {
        "1998-2004": {
          "Continental Test Variant 9": [
            {
              "fitmentLabel": "205/55 R16",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "96H"
            }
          ]
        }
      },
      "260 E 4Matic": {
        "2005-2010": {
          "Continental Test Variant 7": [
            {
              "fitmentLabel": "205/55 R16",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      }
    },
    "Cupra": {
      "Berlingo Multispace": {},
      "Berlingo V.U 475": {},
      "Berlingo V.U 600": {},
      "Berlingo V.U 800": {},
      "Besta": {},
      "Bipper Kombi": {},
      "Bipper Kombi Tepee": {},
      "Blazer": {},
      "Blazer Cheyenne": {},
      "Blazer Cheyenne (2WD)": {},
      "Bluebird": {},
      "Bluebird Kombi": {},
      "Bolt EV": {},
      "Bora": {},
      "Bora 4X4": {},
      "Bora 4X4 Kombi": {},
      "Bora Kombi": {},
      "Born": {},
      "Boxer": {},
      "Boxer 2t800": {},
      "Boxer 2t900": {},
      "Boxer 2t900 4X4": {},
      "Boxer 330": {},
      "Boxer 333": {},
      "Boxer 335": {},
      "Boxer 3t200": {},
      "Boxer 3t300": {},
      "Boxer 3t300 4X4": {},
      "Boxer 3t500": {},
      "Boxer 3t500 4X4": {},
      "Boxer 435": {},
      "Boxer Combi": {},
      "Boxster": {},
      "Boxster GTS": {},
      "Boxster S": {},
      "Boxster S Black Edition": {},
      "Boxster Spyder": {},
      "Boxster T": {},
      "Brava": {},
      "Bravo": {},
      "Brera": {},
      "Brooklands": {},
      "Brooklands Coup\u00e9": {},
      "Business V12": {},
      "Bx": {},
      "147 GTA": {
        "2005-2010": {
          "Continental Test Variant 10": [
            {
              "fitmentLabel": "205/55 R17",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      },
      "260 SE": {
        "2011-2016": {
          "Continental Test Variant 8": [
            {
              "fitmentLabel": "205/55 R16",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 16,
              "speedLoadIndex": "96H"
            }
          ]
        }
      }
    },
    "Dacia": {
      "Bx 4X4": {},
      "Bx 4X4 GTI": {},
      "Bx 4X4 Kombi": {},
      "Bx GTI": {},
      "Bx GTI 16V": {},
      "Bx Kombi": {},
      "C 160": {},
      "C 160 Kombi": {},
      "C 180": {},
      "C 180 CDI": {},
      "C 180 CDI Kombi": {},
      "C 180 CGI": {},
      "C 180 CGI Coup\u00e9": {},
      "C 180 CGI Kombi": {},
      "C 180 Cabrio": {},
      "C 180 Coup\u00e9": {},
      "C 180 D": {},
      "C 180 D Kombi": {},
      "C 180 Kombi": {},
      "C 200": {},
      "C 200 4Matic": {},
      "C 200 4Matic Kombi": {},
      "C 200 CDI": {},
      "C 200 CDI Kombi": {},
      "C 200 CGI": {},
      "C 200 CGI Kombi": {},
      "C 200 Cabrio": {},
      "C 200 Cabrio 4Matic": {},
      "C 200 Coup\u00e9": {},
      "C 200 Coup\u00e9 4Matic": {},
      "C 200 D": {},
      "C 200 D Cabrio": {},
      "C 200 D Coup\u00e9": {},
      "C 200 D Kombi": {},
      "C 200 Kombi": {},
      "C 200 Kombi 4Matic": {},
      "C 200 Kompressor": {},
      "C 220": {},
      "C 220 BlueTec": {},
      "C 220 CDI": {},
      "C 220 CDI Coup\u00e9": {},
      "C 220 CDI Kombi": {},
      "C 220 D": {},
      "C 220 D 4 Matic": {},
      "C 220 D 4Matic": {},
      "155": {
        "2011-2016": {
          "Continental Test Variant 11": [
            {
              "fitmentLabel": "205/55 R17",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "91V"
            }
          ]
        }
      },
      "275 S3": {
        "2017-2021": {
          "Continental Test Variant 9": [
            {
              "fitmentLabel": "205/55 R17",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      }
    },
    "Daewoo": {
      "C 220 D Cabrio": {},
      "C 220 D Cabrio 4Matic": {},
      "C 220 D Coup\u00e9": {},
      "C 220 D Coup\u00e9 4Matic": {},
      "C 220 D Kombi": {},
      "C 220 D Kombi 4Matic": {},
      "C 230": {},
      "C 230 Coup\u00e9": {},
      "C 230 Kombi": {},
      "C 240": {},
      "C 240 4Matic": {},
      "C 240 4Matic Kombi": {},
      "C 240 Kombi": {},
      "C 250": {},
      "C 250 BlueTec": {},
      "C 250 BlueTec 4Matic": {},
      "C 250 CDI": {},
      "C 250 CDI 4Matic": {},
      "C 250 CDI 4Matic Kombi": {},
      "C 250 CDI Coup\u00e9": {},
      "C 250 CDI Kombi": {},
      "C 250 CGI": {},
      "C 250 CGI Kombi": {},
      "C 250 Coup\u00e9": {},
      "C 250 D": {},
      "C 250 D 4Matic Kombi": {},
      "C 250 D Cabrio": {},
      "C 250 D Coup\u00e9": {},
      "C 250 D Kombi": {},
      "C 250 Kombi": {},
      "C 270 CDI": {},
      "C 280": {},
      "C 280 CGI Kombi": {},
      "C 280 Kombi": {},
      "C 30 CDI": {},
      "C 300": {},
      "C 300 BlueTec Hybrid": {},
      "C 300 BlueTec Hybrid Kombi": {},
      "C 300 CDI 4Matic": {},
      "C 300 CDI 4Matic Kombi": {},
      "C 300 Cabrio": {},
      "C 300 Coup\u00e9": {},
      "C 300 D": {},
      "C 300 D 4 Matic Kombi": {},
      "C 300 D 4Matic": {},
      "155 Q4": {
        "2017-2021": {
          "Continental Test Variant 12": [
            {
              "fitmentLabel": "205/55 R17",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      },
      "280": {
        "2022-2026": {
          "Continental Test Variant 10": [
            {
              "fitmentLabel": "205/55 R17",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "91V"
            }
          ]
        }
      }
    },
    "Daihatsu": {
      "C 300 D 4Matic Coup\u00e9": {},
      "C 300 D Coup\u00e9": {},
      "C 300 D Kombi": {},
      "C 300 h": {},
      "C 300 h Kombi": {},
      "C 32": {},
      "C 320 4Matic": {},
      "C 320 4Matic Kombi": {},
      "C 320 CDI": {},
      "C 320 CDI Kombi": {},
      "C 350": {},
      "C 350 4Matic": {},
      "C 350 CDI": {},
      "C 350 CDI Kombi": {},
      "C 350 CGI": {},
      "C 350 CGI 4Matic": {},
      "C 350 CGI Kombi": {},
      "C 350 Coup\u00e9": {},
      "C 350 Kombi": {},
      "C 350 e": {},
      "C 350 e Kombi": {},
      "C 36": {},
      "C 400 4Matic": {},
      "C 400 4Matic Cabrio": {},
      "C 400 4Matic Coup\u00e9": {},
      "C 400 4Matic Kombi": {},
      "C 43": {},
      "C 43 4Matic": {},
      "C 43 4Matic Cabrio": {},
      "C 43 4Matic Coup\u00e9": {},
      "C 43 4Matic Kombi": {},
      "C 43 Cabrio 4Matic": {},
      "C 43 Coup\u00e9 4Matic": {},
      "C 43 Kombi": {},
      "C 43 Kombi 4Matic": {},
      "C 450 4Matic": {},
      "C 450 4Matic Kombi": {},
      "C 55": {},
      "C 55 Kombi": {},
      "C 63": {},
      "C 63 Black Series Coup\u00e9": {},
      "C 63 Coupe": {},
      "C 63 Edition 507": {},
      "C 63 Edition 507 Coup\u00e9": {},
      "C 63 Kombi": {},
      "156": {
        "2022-2026": {
          "Continental Test Variant 1": [
            {
              "fitmentLabel": "205/55 R17",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "96H"
            }
          ]
        }
      },
      "280 Kombi": {
        "1998-2004": {
          "Continental Test Variant 11": [
            {
              "fitmentLabel": "205/55 R17",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      }
    },
    "Dallara": {
      "C 63 S": {},
      "C 63 S Cabrio": {},
      "C 63 S Coupe": {},
      "C 63 S Kombi": {},
      "C 70 Cabrio": {},
      "C-CROSSER": {},
      "C-Elysee": {},
      "C-HR 2WD": {},
      "C-HR 2WD Hybrid": {},
      "C-HR AWD": {},
      "C-HR LE": {},
      "C-Max": {},
      "C-Zero": {},
      "C1": {},
      "C1 II": {},
      "C15 4X4 Dangel": {},
      "C15 Nutzlast 475 kg": {},
      "C15 Nutzlast 600 kg": {},
      "C15 Nutzlast 765 kg": {},
      "C2": {},
      "C2 VTS": {},
      "C25 4x4 Nutzlast 1400 kg": {},
      "C25 Camping Car": {},
      "C25 Nutzlast 1000 kg": {},
      "C25 Nutzlast 1300 kg": {},
      "C25 Nutzlast 1400 kg": {},
      "C25 Nutzlast 1800 kg": {},
      "C3": {},
      "C3 Aircross": {},
      "C3 II": {},
      "C3 III": {},
      "C3 Picasso": {},
      "C3 Pluriel": {},
      "C30": {},
      "C30 Flexifuel": {},
      "C35": {},
      "C4": {},
      "C4 Aircross 4X2": {},
      "C4 Aircross 4X4": {},
      "C4 Cactus": {},
      "C4 Coup\u00e9": {},
      "C4 Grand Picasso": {},
      "C4 II": {},
      "C4 III": {},
      "C4 Picasso": {},
      "156 Crosswagon Q4": {
        "1998-2004": {
          "Continental Test Variant 2": [
            {
              "fitmentLabel": "205/60 R16",
              "width": 205,
              "aspectRatio": 60,
              "diameter": 16,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      },
      "288 GTO": {
        "2005-2010": {
          "Continental Test Variant 12": [
            {
              "fitmentLabel": "205/55 R17",
              "width": 205,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "96H"
            }
          ]
        }
      }
    },
    "De Tomaso": {
      "C4 SpaceTourer": {},
      "C4 VTS": {},
      "C40": {},
      "C5": {},
      "C5 Aircross": {},
      "C5 Aircross Hybrid": {},
      "C5 II": {},
      "C5 II CrossTourer": {},
      "C5 II Tourer": {},
      "C5 II Tourer XTR": {},
      "C5 Kombi": {},
      "C5 X": {},
      "C6": {},
      "C70": {},
      "C8": {},
      "CC": {},
      "CC 4Motion": {},
      "CC8S": {},
      "CCR": {},
      "CCX": {},
      "CCXR": {},
      "CJ 7 Renegade-Texan": {},
      "CJ 7 Standard-Laredo": {},
      "CL 420": {},
      "CL 500": {},
      "CL 500 4Matic": {},
      "CL 55": {},
      "CL 600": {},
      "CL 63": {},
      "CL 65": {},
      "CLA 180": {},
      "CLA 180 CDI": {},
      "CLA 180 D": {},
      "CLA 180 D Shooting Brake": {},
      "CLA 180 Shooting Brake": {},
      "CLA 200": {},
      "CLA 200 CDI": {},
      "CLA 200 CDI 4Matic": {},
      "CLA 200 D": {},
      "CLA 200 D Shooting Brake": {},
      "CLA 200 D Shooting Brake 4 Matic": {},
      "CLA 200 Shooting Brake": {},
      "CLA 220": {},
      "CLA 220 4MATIC": {},
      "CLA 220 CDI": {},
      "156 GTA": {
        "2005-2010": {
          "Continental Test Variant 3": [
            {
              "fitmentLabel": "205/60 R16",
              "width": 205,
              "aspectRatio": 60,
              "diameter": 16,
              "speedLoadIndex": "91V"
            }
          ]
        }
      },
      "296 GTB": {
        "2011-2016": {
          "Continental Test Variant 1": [
            {
              "fitmentLabel": "205/60 R16",
              "width": 205,
              "aspectRatio": 60,
              "diameter": 16,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      }
    },
    "Delorean": {
      "CLA 220 CDI 4Matic": {},
      "CLA 220 D": {},
      "CLA 220 D Shooting Brake": {},
      "CLA 220 D Shooting Brake 4 Matic": {},
      "CLA 220 D Shooting Brake 4Matic": {},
      "CLA 220 Shooting Brake": {},
      "CLA 220 Shooting Brake 4Matic": {},
      "CLA 250": {},
      "CLA 250 4Matic": {},
      "CLA 250 4Matic Shooting Brake": {},
      "CLA 250 Shooting Brake": {},
      "CLA 250 Sport 4Matic Shooting Brake": {},
      "CLA 35 4Matic Coup\u00e9": {},
      "CLA 35 4Matic Shooting Brake": {},
      "CLA 45 4Matic": {},
      "CLA 45 4Matic Shooting Brake": {},
      "CLA 45 A 4Matic Shooting Brake": {},
      "CLA 45 S 4Matic Shooting Brake": {},
      "CLA 45 S 4Matic+ Coup\u00e9": {},
      "CLC 160": {},
      "CLC 180 KOMPRESSOR": {},
      "CLC 200 CDI": {},
      "CLC 200 KOMPRESSOR": {},
      "CLC 220 CDI": {},
      "CLC 230": {},
      "CLC 350": {},
      "CLK 200": {},
      "CLK 200 CGI": {},
      "CLK 200 CGI Cabrio": {},
      "CLK 200 Cabrio": {},
      "CLK 200 Kompressor": {},
      "CLK 200 Kompressor Cabrio": {},
      "CLK 220 CDI": {},
      "CLK 230 Kompressor": {},
      "CLK 230 Kompressor Cabrio": {},
      "CLK 240": {},
      "CLK 240 Cabrio": {},
      "CLK 270 CDI": {},
      "CLK 280": {},
      "CLK 280 Cabrio": {},
      "CLK 320": {},
      "CLK 320 CDI": {},
      "CLK 320 CDI Cabrio": {},
      "CLK 320 Cabrio": {},
      "CLK 350": {},
      "156 Q System": {
        "2011-2016": {
          "Continental Test Variant 4": [
            {
              "fitmentLabel": "205/60 R16",
              "width": 205,
              "aspectRatio": 60,
              "diameter": 16,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      },
      "29L10": {
        "2017-2021": {
          "Continental Test Variant 2": [
            {
              "fitmentLabel": "205/60 R16",
              "width": 205,
              "aspectRatio": 60,
              "diameter": 16,
              "speedLoadIndex": "91V"
            }
          ]
        }
      }
    },
    "Devinci": {
      "CLK 350 Cabrio": {},
      "CLK 430": {},
      "CLK 430 Cabrio": {},
      "CLK 500": {},
      "CLK 500 Cabrio": {},
      "CLK 55": {},
      "CLK 55 Cabrio": {},
      "CLK 63": {},
      "CLK 63 Black Series": {},
      "CLK 63 Cabrio": {},
      "CLS 220 BlueTec": {},
      "CLS 220 BlueTec Shooting Brake": {},
      "CLS 250 BlueTec": {},
      "CLS 250 BlueTec 4Matic": {},
      "CLS 250 BlueTec 4Matic Shooting Brake": {},
      "CLS 250 BlueTec Shooting Brake": {},
      "CLS 250 CDI": {},
      "CLS 280": {},
      "CLS 300 D": {},
      "CLS 320 CDI": {},
      "CLS 350": {},
      "CLS 350 BlueTec": {},
      "CLS 350 BlueTec 4Matic": {},
      "CLS 350 BlueTec 4Matic Shooting Brake": {},
      "CLS 350 BlueTec Shooting Brake": {},
      "CLS 350 CDI": {},
      "CLS 350 D": {},
      "CLS 350 D 4Matic": {},
      "CLS 350 D 4Matic Shooting Brake": {},
      "CLS 350 D Shooting Brake": {},
      "CLS 400": {},
      "CLS 400 4Matic": {},
      "CLS 400 4Matic Shooting Brake": {},
      "CLS 400 D 4Matic": {},
      "CLS 400 Shooting Brake": {},
      "CLS 450 4Matic": {},
      "CLS 500": {},
      "CLS 500 4Matic": {},
      "CLS 500 4Matic Shooting Brake": {},
      "CLS 500 Shooting Brake": {},
      "CLS 53 4Matic": {},
      "CLS 55": {},
      "CLS 63": {},
      "CLS 63 4Matic": {},
      "CLS 63 4Matic Shooting Brake": {},
      "156 Sportwagon": {
        "2017-2021": {
          "Continental Test Variant 5": [
            {
              "fitmentLabel": "205/60 R16",
              "width": 205,
              "aspectRatio": 60,
              "diameter": 16,
              "speedLoadIndex": "96H"
            }
          ]
        }
      },
      "29L11": {
        "2022-2026": {
          "Continental Test Variant 3": [
            {
              "fitmentLabel": "205/60 R16",
              "width": 205,
              "aspectRatio": 60,
              "diameter": 16,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      }
    },
    "Dodge": {
      "CLS 63 S 4Matic": {},
      "CLS 63 S 4Matic Shooting Brake": {},
      "CR-V": {},
      "CR-V II": {},
      "CR-V II 2WD": {},
      "CR-V III": {},
      "CR-V IV": {},
      "CR-V IV 2WD": {},
      "CR-V V 2WD": {},
      "CR-V V 4WD": {},
      "CR-Z": {},
      "CRX": {},
      "CRX del Sol \u00e9mio": {},
      "CRX del sol": {},
      "CT 200h": {},
      "CT6": {},
      "CT6 AWD": {},
      "CT6 Plug In": {},
      "CTS": {},
      "CTS AWD": {},
      "CTS Coup\u00e9": {},
      "CTS Sport Wagon": {},
      "CTS-V": {},
      "CTS-V Coup\u00e9": {},
      "CTS-V Sport": {},
      "CTS-V Sport Wagon": {},
      "CV 8": {},
      "CX-3 (4X2)": {},
      "CX-3 (4X4)": {},
      "CX-30": {},
      "CX-30 4X4": {},
      "CX-5 (4X2)": {},
      "CX-5 (4X4)": {},
      "CX-60": {},
      "CX-7": {},
      "CX-9": {},
      "Cabrio": {},
      "Cabstar": {},
      "Caddy": {},
      "Caddy 4Motion": {},
      "Caddy Pick up": {},
      "Caddy Van": {},
      "Caddy Van 4Motion": {},
      "Caliber": {},
      "Caliber SRT4": {},
      "156 Sportwagon GTA": {
        "2022-2026": {
          "Continental Test Variant 6": [
            {
              "fitmentLabel": "215/55 R17",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "105V"
            }
          ]
        }
      },
      "29L12": {
        "1998-2004": {
          "Continental Test Variant 4": [
            {
              "fitmentLabel": "205/60 R16",
              "width": 205,
              "aspectRatio": 60,
              "diameter": 16,
              "speedLoadIndex": "96H"
            }
          ]
        }
      }
    },
    "Ds": {
      "Calibra": {},
      "Calibra 4X4": {},
      "California": {},
      "California 4Motion": {},
      "California Beach": {},
      "California Beach 4Motion": {},
      "California T": {},
      "California Van": {},
      "California Van 4Motion": {},
      "Camaro": {},
      "Camaro Cabrio": {},
      "Camaro Cabrio (Performance Package)": {},
      "Camaro Coup\u00e9": {},
      "Camaro LS Coupe": {},
      "Camaro SS": {},
      "Camaro SS 1LE": {},
      "Camaro SS Cabrio": {},
      "Camaro SS Coup\u00e9": {},
      "Camaro ZL1 1LE": {},
      "Camaro ZL1 Cabrio": {},
      "Camaro ZL1 Coup\u00e9": {},
      "Campo": {},
      "Camry": {},
      "Camry Hybrid": {},
      "Camry Kombi": {},
      "Camry XLE V6": {},
      "Camry XSE": {},
      "Camry XSE V6": {},
      "Canter": {},
      "Canter 3C11": {},
      "Canter 3C13": {},
      "Canter 3C15": {},
      "Canter 3S11": {},
      "Canter 3S13": {},
      "Canter 6C14": {},
      "Canter 6C18": {},
      "Canter 7C15 Hybrid": {},
      "Captiva": {},
      "Captiva Sport LS": {},
      "Captiva Sport LT": {},
      "Captiva Sport LTZ": {},
      "Captur": {},
      "Caravelle": {},
      "Caravelle 4Motion": {},
      "Carens": {},
      "156 Sportwagon Q System": {
        "1998-2004": {
          "Continental Test Variant 7": [
            {
              "fitmentLabel": "215/55 R17",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      },
      "29L13": {
        "2005-2010": {
          "Continental Test Variant 5": [
            {
              "fitmentLabel": "215/55 R17",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "105V"
            }
          ]
        }
      }
    },
    "Ferrari": {
      "Carina E": {},
      "Carina E Kombi": {},
      "Carina II": {},
      "Carisma": {},
      "Carnival": {},
      "Carrera GT": {},
      "Carry": {},
      "Carry  Tray": {},
      "Cascada": {},
      "Cayenne": {},
      "Cayenne Coupe": {},
      "Cayenne GTS": {},
      "Cayenne II": {},
      "Cayenne II  Turbo": {},
      "Cayenne II  Turbo S": {},
      "Cayenne II Diesel": {},
      "Cayenne II GTS": {},
      "Cayenne II S": {},
      "Cayenne II S Diesel": {},
      "Cayenne II S E-Hybrid": {},
      "Cayenne II S Hybrid": {},
      "Cayenne II S S Diesel": {},
      "Cayenne II Turbo": {},
      "Cayenne III": {},
      "Cayenne III E-Hybrid": {},
      "Cayenne III S": {},
      "Cayenne III Turbo": {},
      "Cayenne III Turbo S E-Hybrid": {},
      "Cayenne III Turbo S E-Hybrid Coupe": {},
      "Cayenne S": {},
      "Cayenne Turbo": {},
      "Cayenne Turbo S": {},
      "Cayman": {},
      "Cayman GT4": {},
      "Cayman GTS": {},
      "Cayman R": {},
      "Cayman S": {},
      "Cayman T": {},
      "Cee'd": {},
      "Cee'd GT": {},
      "Cee'd SW": {},
      "Ceed": {},
      "Ceed SW": {},
      "Celerio": {},
      "Celica Coup\u00e9": {},
      "159": {
        "2005-2010": {
          "Continental Test Variant 8": [
            {
              "fitmentLabel": "215/55 R17",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "94V"
            }
          ]
        }
      },
      "29L14": {
        "2011-2016": {
          "Continental Test Variant 6": [
            {
              "fitmentLabel": "215/55 R17",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      }
    },
    "Fiat": {
      "Celica GT Coup\u00e9": {},
      "Celica GT-Four ST205": {},
      "Celica GT-S Coup\u00e9": {},
      "Centenario": {},
      "Centenario Roadster": {},
      "Cerato": {},
      "Cerbera": {},
      "Cevennes": {},
      "Charade": {},
      "Cherokee": {},
      "Cherokee 2WD": {},
      "Cherokee 4x2": {},
      "Chimaera 450": {},
      "Chiron": {},
      "Chiron Pur Sport": {},
      "Cinquecento": {},
      "Cinquecento Elektrisch": {},
      "Citan Combi": {},
      "Citan Kleintransporter": {},
      "Citigo": {},
      "City": {},
      "City-Coup\u00e9": {},
      "City-Coup\u00e9 BRABUS": {},
      "Civic": {},
      "Civic 4-T\u00fcren": {},
      "Civic Aerodeck": {},
      "Civic Aerodeck 4WD": {},
      "Civic Coup\u00e9": {},
      "Civic Sedan": {},
      "Civic Tourer": {},
      "Civic Type R": {},
      "Clarity Elektrisch": {},
      "Clarity Fuel Cell": {},
      "Clarity Hybrid": {},
      "Clarus": {},
      "Classic DB718": {},
      "Clio": {},
      "Clio 16S": {},
      "Clio II": {},
      "Clio II Campus": {},
      "Clio II RS Trophy": {},
      "Clio III": {},
      "Clio III Estate": {},
      "Clio III GT": {},
      "Clio III Gordini RS": {},
      "159 Q4": {
        "2011-2016": {
          "Continental Test Variant 9": [
            {
              "fitmentLabel": "215/55 R17",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "94W"
            }
          ]
        }
      },
      "29L15": {
        "2017-2021": {
          "Continental Test Variant 7": [
            {
              "fitmentLabel": "215/55 R17",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "94V"
            }
          ]
        }
      }
    },
    "Fisker": {
      "Clio III RS": {},
      "Clio III RS Ange et Demon": {},
      "Clio III RS F1 Team": {},
      "Clio III RS ph2": {},
      "Clio IV": {},
      "Clio IV Estate": {},
      "Clio IV Estate GT": {},
      "Clio IV GT": {},
      "Clio IV RS": {},
      "Clio IV RS Trophy": {},
      "Clio RS - Ragnotti": {},
      "Clio RS1": {},
      "Clio RS2": {},
      "Clio RS3 (RS 2004)": {},
      "Clio V": {},
      "Clio V6 ph1": {},
      "Clio V6 ph2": {},
      "Clio Williams": {},
      "Colt": {},
      "Colt CZ3": {},
      "Colt CZC": {},
      "Colt CZT": {},
      "Colt Gti": {},
      "Combi Type 2": {},
      "Combo": {},
      "Combo Cargo": {},
      "Combo Life": {},
      "Combo Tour": {},
      "Combo-e Life": {},
      "Commander": {},
      "Compass": {},
      "Compass II 4x2": {},
      "Compass II 4x4": {},
      "Concerto": {},
      "Connect II": {},
      "Connect kurz": {},
      "Connect lang": {},
      "Continental": {},
      "Continental Flying Spur": {},
      "Continental Flying Spur Speed": {},
      "Continental GT": {},
      "Continental GT Cabrio": {},
      "Continental GT Speed": {},
      "Continental GT V8": {},
      "Continental GT V8 S": {},
      "159 Sportwagon": {
        "2017-2021": {
          "Continental Test Variant 10": [
            {
              "fitmentLabel": "215/55 R17",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "98V"
            }
          ]
        }
      },
      "2er Active Tourer": {
        "2022-2026": {
          "Continental Test Variant 8": [
            {
              "fitmentLabel": "215/55 R17",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "94W"
            }
          ]
        }
      }
    },
    "Ford": {
      "Continental GT3-R": {},
      "Continental GTC": {},
      "Continental GTC Speed": {},
      "Continental GTC V8": {},
      "Continental GTC V8 S": {},
      "Continental R": {},
      "Continental Supersports": {},
      "Continental Supersports Cabrio": {},
      "Continental Supersports ISR Cabrio": {},
      "Cooper Clubman": {},
      "Cooper Countryman": {},
      "Cooper Countryman AWD": {},
      "Cooper Countryman SE": {},
      "Cooper Countryman SE AWD": {},
      "Cooper D Clubman": {},
      "Cooper D Countryman": {},
      "Cooper D Countryman AWD": {},
      "Cooper D Paceman": {},
      "Cooper D Paceman All4": {},
      "Cooper Paceman": {},
      "Cooper Paceman All4": {},
      "Cooper S Clubman": {},
      "Cooper S Clubman All4": {},
      "Cooper S Countryman": {},
      "Cooper S Countryman AWD": {},
      "Cooper S Paceman": {},
      "Cooper S Paceman All4": {},
      "Cooper SD Clubman": {},
      "Cooper SD Clubman All4": {},
      "Cooper SD Countryman": {},
      "Cooper SD Countryman AWD": {},
      "Cooper SD Paceman": {},
      "Cooper SD Paceman All4": {},
      "Copen": {},
      "Cordoba I": {},
      "Cordoba I Cupra": {},
      "Cordoba I GT/GTI": {},
      "Cordoba I Vario": {},
      "Cordoba II": {},
      "Cordoba II Cupra": {},
      "Corniche IV": {},
      "Corolla": {},
      "Corolla Coup\u00e9": {},
      "Corolla Kombi": {},
      "Corolla Limousine": {},
      "159 Sportwagon Q4": {
        "2022-2026": {
          "Continental Test Variant 11": [
            {
              "fitmentLabel": "215/55 R18",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      },
      "2er Cabrio": {
        "1998-2004": {
          "Continental Test Variant 9": [
            {
              "fitmentLabel": "215/55 R17",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 17,
              "speedLoadIndex": "98V"
            }
          ]
        }
      }
    },
    "Genesis": {
      "Corolla TS": {},
      "Corolla Touring Sports": {},
      "Corolla Verso": {},
      "Corona": {},
      "Corona Combi": {},
      "Corona Liftback": {},
      "Corrado": {},
      "Corrado G60": {},
      "Corrado VR6": {},
      "Corsa A": {},
      "Corsa A GSI": {},
      "Corsa A GT": {},
      "Corsa A van": {},
      "Corsa B": {},
      "Corsa B GSI 16V": {},
      "Corsa B Sport": {},
      "Corsa B van": {},
      "Corsa C": {},
      "Corsa C GSI": {},
      "Corsa D": {},
      "Corsa D OPC": {},
      "Corsa D OPC Nurburgring": {},
      "Corsa E": {},
      "Corsa E GSI": {},
      "Corsa E OPC": {},
      "Corsa E S": {},
      "Corsa F": {},
      "Corvette C4": {},
      "Corvette C5": {},
      "Corvette C5 50th anniversary": {},
      "Corvette C5 Cabrio": {},
      "Corvette C5 Hatchback": {},
      "Corvette C5 Z06": {},
      "Corvette C6": {},
      "Corvette C6 Cabrio": {},
      "Corvette C6 Grand Sport": {},
      "Corvette C6 Grand Sport Cabrio": {},
      "Corvette C6 Z06": {},
      "Corvette C7 Grand Sport": {},
      "Corvette C7 Grand Sport Cabrio": {},
      "Corvette C7 Stingray": {},
      "Corvette C7 Stingray Cabrio": {},
      "Corvette C7 Z06": {},
      "Corvette C7 Z06 Cabrio": {},
      "Corvette C7 ZR1": {},
      "160": {
        "1998-2004": {
          "Continental Test Variant 12": [
            {
              "fitmentLabel": "215/55 R18",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "91V"
            }
          ]
        }
      },
      "2er Coup\u00e9": {
        "2005-2010": {
          "Continental Test Variant 10": [
            {
              "fitmentLabel": "215/55 R18",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      }
    },
    "Gumpert": {
      "Corvette C8 Stingray 1LT Cabrio": {},
      "Corvette C8 Stingray 1LT Z51": {},
      "Corvette C8 Stingray 1LT Z51 Cabrio": {},
      "Corvette C8 Stingray 2LT": {},
      "Corvette C8 Stingray 2LT Cabrio": {},
      "Corvette C8 Stingray 2LT Z51": {},
      "Corvette C8 Stingray 2LT Z51 Cabrio": {},
      "Corvette C8 Stingray 3LT": {},
      "Corvette C8 Stingray 3LT Cabrio": {},
      "Corvette C8 Stingray 3LT Z51": {},
      "Corvette C8 Stingray 3LT Z51 Cabrio": {},
      "Corvette ZR1": {},
      "Cougar": {},
      "Cougar ST 200": {},
      "Countach": {},
      "Coup\u00e9": {},
      "Coup\u00e9 407": {},
      "Coup\u00e9 407 GT": {},
      "Coup\u00e9 Quattro": {},
      "Courier": {},
      "Crafter Combi 30": {},
      "Crafter Combi 35": {},
      "Crafter Kleintransporter": {},
      "Crafter Van 30": {},
      "Crafter Van 35": {},
      "Crafter Van 50": {},
      "Crafter einfache Pritsche": {},
      "Croma": {},
      "Croma II": {},
      "Cross Caddy": {},
      "Cross Polo IV": {},
      "Cross Polo V": {},
      "Cross Touran": {},
      "Cross-up!": {},
      "Crossblade": {},
      "Crossfire Cabrio": {},
      "Crossfire Coup\u00e9": {},
      "Crossfire SRT6 Cabrio": {},
      "Crossfire SRT6 Coup\u00e9": {},
      "Crossland X": {},
      "Crossline": {},
      "Crossover": {},
      "Crosstrek": {},
      "Crosstrek Hybrid": {},
      "Crosswagon": {},
      "164": {
        "2005-2010": {
          "Continental Test Variant 1": [
            {
              "fitmentLabel": "215/55 R18",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "94W"
            }
          ]
        }
      },
      "2er Gran Coup\u00e9": {
        "2011-2016": {
          "Continental Test Variant 11": [
            {
              "fitmentLabel": "215/55 R18",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "91V"
            }
          ]
        }
      }
    },
    "Hennessey": {
      "Cruze": {},
      "Cruze SW": {},
      "Cube": {},
      "Cullinan": {},
      "Cuore": {},
      "Cx 25 Turbo": {},
      "Cx Evasion": {},
      "Cygnet": {},
      "D 10": {},
      "D 10 Touring": {},
      "D 3 Biturbo": {},
      "D 3 Biturbo (F30)": {},
      "D 3 Biturbo Touring (F31)": {},
      "D 3 Biturbo Touring (F31) Allrad": {},
      "D 4 Biturbo Cabrio (F33)": {},
      "D 4 Biturbo Coupe (F32)": {},
      "D 5 Biturbo": {},
      "D 5 Biturbo Touring": {},
      "D 5 S": {},
      "D 5 S Touring": {},
      "D-Max 4X2": {},
      "D-Max 4X2 Nutzfahrzeug": {},
      "D-Max 4X4": {},
      "D-Max Artic Trucks AT35": {},
      "DB11 AMR Heritage": {},
      "DB11 New Heritage": {},
      "DB11 Pop Pioneer": {},
      "DB11 Volante Intrepid Sport": {},
      "DB11 Volante New Heritage": {},
      "DB11 Volante Open Aura": {},
      "DB11 Volante Twilight Tour": {},
      "DB7 GT": {},
      "DB7 Vantage": {},
      "DB7 Vantage Coup\u00e9": {},
      "DB7 Vantage Volante": {},
      "DB7 Zagato": {},
      "DB9": {},
      "DB9 Carbon Edition": {},
      "DB9 GT": {},
      "DB9 GT Volante": {},
      "DB9 Volante": {},
      "DBS Coup\u00e9": {},
      "DBS Superleggera Distilled Energy": {},
      "DBS Superleggera Volante Elemental": {},
      "DBS Superleggera Volante Resolute": {},
      "164 Q4": {
        "2011-2016": {
          "Continental Test Variant 2": [
            {
              "fitmentLabel": "215/55 R18",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "96H"
            }
          ]
        }
      },
      "2er Gran Tourer": {
        "2017-2021": {
          "Continental Test Variant 12": [
            {
              "fitmentLabel": "215/55 R18",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "94W"
            }
          ]
        }
      }
    },
    "Hommel": {
      "DBS Superleggera Volante Volcanic": {},
      "DBS Volante": {},
      "DBX": {},
      "DMC-12": {},
      "DS 3": {},
      "DS 3 Cabrio": {},
      "DS 3 Crossback": {},
      "DS 3 Crossback E-Tense": {},
      "DS 3 Performance": {},
      "DS 3 Racing": {},
      "DS 3 Racing Cabrio": {},
      "DS 4": {},
      "DS 4 Crossback": {},
      "DS 4 II": {},
      "DS 5": {},
      "DS 7 Crossback": {},
      "DS 9": {},
      "DS 9 Hybrid": {},
      "Daimler": {},
      "Dawn": {},
      "Daytona SP3": {},
      "DeVille": {},
      "Dedra": {},
      "Dedra 4X4": {},
      "Dedra GT": {},
      "Dedra SW": {},
      "Dedra SW 4X4": {},
      "Defender 110": {},
      "Defender 130": {},
      "Defender 90": {},
      "Delta I": {},
      "Delta I 4X4": {},
      "Delta I HF 4WD": {},
      "Delta I HF Integrale": {},
      "Delta I HF Turbo": {},
      "Delta II": {},
      "Delta II 4X4": {},
      "Delta II HPE HF": {},
      "Delta II LS HF": {},
      "Delta III": {},
      "Demio": {},
      "Diablo": {},
      "Diablo GT": {},
      "Diablo Roadster": {},
      "Discovery": {},
      "165": {
        "2017-2021": {
          "Continental Test Variant 3": [
            {
              "fitmentLabel": "215/60 R17",
              "width": 215,
              "aspectRatio": 60,
              "diameter": 17,
              "speedLoadIndex": "91H"
            }
          ]
        }
      },
      "3": {
        "2022-2026": {
          "Continental Test Variant 1": [
            {
              "fitmentLabel": "215/55 R18",
              "width": 215,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "96H"
            }
          ]
        }
      }
    },
    "Honda": {
      "Discovery II": {},
      "Discovery III": {},
      "Discovery IV": {},
      "Discovery Sport": {},
      "Discovery Sport 4x2": {},
      "Discovery V": {},
      "Doblo": {},
      "Doblo Cargo": {},
      "Dokker": {},
      "Dokker Stepway": {},
      "Dokker Van": {},
      "Domino": {},
      "Ducato (PTAC 3000)": {},
      "Ducato (PTAC 3300)": {},
      "Ducato (PTAC 3500 Light)": {},
      "Ducato (PTAC 3500 Maxi)": {},
      "Ducato (PTAC 3500)": {},
      "Ducato 10": {},
      "Ducato 10 4X4 Dangel": {},
      "Ducato 10 Camping Car": {},
      "Ducato 11": {},
      "Ducato 14": {},
      "Ducato 14 4X4 Dangel": {},
      "Ducato 14 Camping Car": {},
      "Ducato 15": {},
      "Ducato 9": {},
      "Ducato Maxi": {},
      "Ducato Maxi 4X4 Dangel": {},
      "Ducato Maxi Camping Car": {},
      "Ducato Maxi Mum": {},
      "Duster 4x2": {},
      "Duster 4x4": {},
      "Duster II 4x2": {},
      "Duster II 4x4": {},
      "E 200": {},
      "E 200 4 Matic Kombi": {},
      "E 200 4Matic": {},
      "E 200 B20": {},
      "E 200 BlueTec": {},
      "E 200 BlueTec Kombi": {},
      "E 200 CDI": {},
      "E 200 CDI Kombi": {},
      "E 200 CGI": {},
      "E 200 CGI Cabrio": {},
      "E 200 CGI Coup\u00e9": {},
      "166": {
        "2022-2026": {
          "Continental Test Variant 4": [
            {
              "fitmentLabel": "215/60 R17",
              "width": 215,
              "aspectRatio": 60,
              "diameter": 17,
              "speedLoadIndex": "94V"
            }
          ]
        }
      },
      "3 Limousine": {
        "1998-2004": {
          "Continental Test Variant 2": [
            {
              "fitmentLabel": "215/60 R17",
              "width": 215,
              "aspectRatio": 60,
              "diameter": 17,
              "speedLoadIndex": "91H"
            }
          ]
        }
      }
    },
    "Hummer": {
      "E 200 CGI Kombi": {},
      "E 200 Cabrio": {},
      "E 200 Cabrio 4Matic": {},
      "E 200 Coup\u00e9": {},
      "E 200 Coup\u00e9 4Matic": {},
      "E 200 D": {},
      "E 200 D Kombi": {},
      "E 200 Kombi": {},
      "E 200 Kombi 4Matic": {},
      "E 200 Kompressor": {},
      "E 200 Kompressor Kombi": {},
      "E 200 NGT": {},
      "E 200d": {},
      "E 220": {},
      "E 220 BlueTec": {},
      "E 220 BlueTec 4Matic Kombi": {},
      "E 220 BlueTec Kombi": {},
      "E 220 Bluetec Cabrio": {},
      "E 220 Bluetec Coup\u00e9": {},
      "E 220 CDI": {},
      "E 220 CDI Cabrio": {},
      "E 220 CDI Coup\u00e9": {},
      "E 220 CDI Kombi": {},
      "E 220 Cabrio": {},
      "E 220 Coup\u00e9": {},
      "E 220 D": {},
      "E 220 D 4Matic": {},
      "E 220 D All Terrain Kombi": {},
      "E 220 D Cabrio": {},
      "E 220 D Cabrio 4Matic": {},
      "E 220 D Coup\u00e9": {},
      "E 220 D Coup\u00e9 4Matic": {},
      "E 220 D Kombi": {},
      "E 220 Kombi": {},
      "E 230": {},
      "E 230 4Matic": {},
      "E 230 Kombi": {},
      "E 240": {},
      "E 240 4Matic": {},
      "E 240 Kombi": {},
      "E 250": {},
      "E 250 BlueTec": {},
      "E 250 BlueTec 4Matic": {},
      "E 250 BlueTec 4Matic Kombi": {},
      "E 250 BlueTec Kombi": {},
      "175 CSR": {
        "1998-2004": {
          "Continental Test Variant 5": [
            {
              "fitmentLabel": "215/60 R17",
              "width": 215,
              "aspectRatio": 60,
              "diameter": 17,
              "speedLoadIndex": "94W"
            }
          ]
        }
      },
      "3 MPS": {
        "2005-2010": {
          "Continental Test Variant 3": [
            {
              "fitmentLabel": "215/60 R17",
              "width": 215,
              "aspectRatio": 60,
              "diameter": 17,
              "speedLoadIndex": "94V"
            }
          ]
        }
      }
    },
    "Hyundai": {
      "E 250 Bluetec Cabrio": {},
      "E 250 Bluetec Coup\u00e9": {},
      "E 250 CDI": {},
      "E 250 CDI 4Matic": {},
      "E 250 CDI 4Matic Kombi": {},
      "E 250 CDI Cabrio": {},
      "E 250 CDI Coup\u00e9": {},
      "E 250 CDI Kombi": {},
      "E 250 CGI": {},
      "E 250 CGI Cabrio": {},
      "E 250 CGI Coup\u00e9": {},
      "E 250 CGI Kombi": {},
      "E 250 Cabrio": {},
      "E 250 Coup\u00e9": {},
      "E 250 Kombi": {},
      "E 250 TD": {},
      "E 250 TD Kombi": {},
      "E 270 CDI": {},
      "E 270 CDI Kombi": {},
      "E 280": {},
      "E 280 4Matic": {},
      "E 280 4Matic Kombi": {},
      "E 280 CDI": {},
      "E 280 CDI 4Matic": {},
      "E 280 CDI Kombi": {},
      "E 280 Kombi": {},
      "E 290 TD": {},
      "E 290 TD Kombi": {},
      "E 300": {},
      "E 300 4Matic": {},
      "E 300 4Matic Kombi": {},
      "E 300 Bluetec": {},
      "E 300 Bluetec Hybrid": {},
      "E 300 Bluetec Hybrid Kombi": {},
      "E 300 Bluetec Kombi": {},
      "E 300 CDI": {},
      "E 300 CDI 4Matic": {},
      "E 300 CDI 4Matic Kombi": {},
      "E 300 CDI Kombi": {},
      "E 300 Cabrio": {},
      "E 300 Coup\u00e9": {},
      "E 300 DE": {},
      "E 300 DE Kombi": {},
      "E 300 Kombi": {},
      "E 300 TD Kombi": {},
      "190": {
        "2005-2010": {
          "Continental Test Variant 6": [
            {
              "fitmentLabel": "215/60 R17",
              "width": 215,
              "aspectRatio": 60,
              "diameter": 17,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      },
      "3 Wheeler": {
        "2011-2016": {
          "Continental Test Variant 4": [
            {
              "fitmentLabel": "215/60 R17",
              "width": 215,
              "aspectRatio": 60,
              "diameter": 17,
              "speedLoadIndex": "94W"
            }
          ]
        }
      }
    },
    "Infiniti": {
      "E 320": {},
      "E 320 4Matic": {},
      "E 320 4Matic Kombi": {},
      "E 320 CDI": {},
      "E 320 CDI 4Matic": {},
      "E 320 CDI Kombi": {},
      "E 320 Cabrio": {},
      "E 320 Coup\u00e9": {},
      "E 320 Kombi": {},
      "E 320-T CDI": {},
      "E 350": {},
      "E 350 4Matic": {},
      "E 350 4Matic Kombi": {},
      "E 350 Bluetec": {},
      "E 350 Bluetec 4Matic": {},
      "E 350 Bluetec 4Matic Kombi": {},
      "E 350 Bluetec Cabrio": {},
      "E 350 Bluetec Coup\u00e9": {},
      "E 350 Bluetec Kombi": {},
      "E 350 CDI": {},
      "E 350 CDI 4Matic": {},
      "E 350 CDI 4Matic Kombi": {},
      "E 350 CDI Cabrio": {},
      "E 350 CDI Coup\u00e9": {},
      "E 350 CDI Kombi": {},
      "E 350 CGI": {},
      "E 350 CGI Cabrio": {},
      "E 350 CGI Coup\u00e9": {},
      "E 350 CGI Kombi": {},
      "E 350 Cabrio": {},
      "E 350 Coup\u00e9": {},
      "E 350 Coup\u00e9 4Matic": {},
      "E 350 D": {},
      "E 350 D 4Matic Kombi": {},
      "E 350 D All Terrain Kombi": {},
      "E 350 D Cabrio": {},
      "E 350 D Coup\u00e9": {},
      "E 350 D Kombi": {},
      "E 350 E": {},
      "E 350 Kombi": {},
      "E 400": {},
      "E 400 4Matic": {},
      "E 400 4Matic Cabrio": {},
      "E 400 4Matic Kombi": {},
      "E 400 CDI": {},
      "190 E": {
        "2011-2016": {
          "Continental Test Variant 7": [
            {
              "fitmentLabel": "215/65 R16",
              "width": 215,
              "aspectRatio": 65,
              "diameter": 16,
              "speedLoadIndex": "105V"
            }
          ]
        }
      },
      "3-Eleven 430": {
        "2017-2021": {
          "Continental Test Variant 5": [
            {
              "fitmentLabel": "215/60 R17",
              "width": 215,
              "aspectRatio": 60,
              "diameter": 17,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      }
    },
    "Isuzu": {
      "E 400 Cabrio": {},
      "E 400 Coup\u00e9": {},
      "E 400 Coup\u00e9 4Matic": {},
      "E 400 D": {},
      "E 400 D 4Matic": {},
      "E 400 D 4Matic Cabrio": {},
      "E 400 D 4Matic Coup\u00e9": {},
      "E 400 D 4Matic Kombi": {},
      "E 400 D All Terrain Kombi": {},
      "E 400 D Kombi": {},
      "E 400 Kombi": {},
      "E 420": {},
      "E 420 CDI": {},
      "E 420 Kombi": {},
      "E 43 4Matic": {},
      "E 43 4Matic Kombi": {},
      "E 430": {},
      "E 430 4Matic": {},
      "E 430 4Matic Kombi": {},
      "E 430 Kombi": {},
      "E 450 4Matic Cabrio": {},
      "E 450 4Matic Coup\u00e9": {},
      "E 450 Kombi 4Matic": {},
      "E 50": {},
      "E 500": {},
      "E 500 4Matic": {},
      "E 500 4Matic Kombi": {},
      "E 500 Cabrio": {},
      "E 500 Coup\u00e9": {},
      "E 500 Kombi": {},
      "E 53 4Matic": {},
      "E 53 Cabrio 4Matic": {},
      "E 53 Coup\u00e9 4Matic": {},
      "E 53 Kombi 4Matic": {},
      "E 55": {},
      "E 55 4Matic": {},
      "E 55 4Matic Kombi": {},
      "E 55 Kombi": {},
      "E 63": {},
      "E 63 4Matic": {},
      "E 63 4Matic Kombi": {},
      "E 63 Kombi": {},
      "E 63 S": {},
      "E 63 S 4Matic": {},
      "E 63 S 4Matic Kombi": {},
      "190 Evolution II": {
        "2017-2021": {
          "Continental Test Variant 8": [
            {
              "fitmentLabel": "215/65 R16",
              "width": 215,
              "aspectRatio": 65,
              "diameter": 16,
              "speedLoadIndex": "91H"
            }
          ]
        }
      },
      "3-Eleven Race": {
        "2022-2026": {
          "Continental Test Variant 6": [
            {
              "fitmentLabel": "215/65 R16",
              "width": 215,
              "aspectRatio": 65,
              "diameter": 16,
              "speedLoadIndex": "105V"
            }
          ]
        }
      }
    },
    "Iveco": {
      "E 63 S 700": {},
      "E 63 S Kombi": {},
      "E City": {},
      "E V12 800": {},
      "E-Cell": {},
      "E-Mehari": {},
      "E-NV200 Evalia": {},
      "E-Pace D150": {},
      "E-Pace D150 AWD": {},
      "E-Pace D180 AWD": {},
      "E-Pace D240 AWD": {},
      "E-Pace P200 AWD": {},
      "E-Pace P250 AWD": {},
      "E-Pace P300 AWD": {},
      "E-Soul II": {},
      "E-Tron 55 Quattro": {},
      "E-Tron GT Quattro": {},
      "E2000": {},
      "E2200": {},
      "EB 110": {},
      "EHS": {},
      "EQ ForFour": {},
      "EQ Fortwo": {},
      "EQ Fortwo Cabrio": {},
      "EQA 250": {},
      "EQA 300 4Matic": {},
      "EQA 350 4Matic": {},
      "EQB 250": {},
      "EQB 300 4MATIC": {},
      "EQB 350 4MATIC": {},
      "EQC 400 4Matic": {},
      "EQE 350": {},
      "EQE 43 4Matic": {},
      "EQS 350": {},
      "EQS 450+": {},
      "EQS 580 4Matic": {},
      "EQS SUV 450 4MATIC": {},
      "ES": {},
      "EV6": {},
      "EV6 GT": {},
      "EX30d": {},
      "EX35": {},
      "EX37": {},
      "Eclipse Cross": {},
      "Eclipse Cross AWD": {},
      "1er Cabrio": {
        "2022-2026": {
          "Continental Test Variant 9": [
            {
              "fitmentLabel": "215/65 R16",
              "width": 215,
              "aspectRatio": 65,
              "diameter": 16,
              "speedLoadIndex": "94V"
            }
          ]
        }
      }
    },
    "Jaguar": {
      "Ecosport": {},
      "Ecosport AWD": {},
      "Edge": {},
      "Edge 2WD": {},
      "Elan": {},
      "Elantra": {},
      "Elantra Coup\u00e9": {},
      "Eldorado": {},
      "Elise": {},
      "Elise 111R": {},
      "Elise 111S": {},
      "Elise CR": {},
      "Elise Cup 250": {},
      "Elise Cup R": {},
      "Elise S": {},
      "Elise S1": {},
      "Elise Sport 190": {},
      "Elise Sport 220": {},
      "Elise Sports Tourer": {},
      "Elise S\u00e9rie K": {},
      "Elva": {},
      "Enyaq 50 iV": {},
      "Enyaq 60 iV": {},
      "Enyaq 60 iV Coup\u00e9": {},
      "Enyaq 80 iV": {},
      "Enyaq 80 iV Coup\u00e9": {},
      "Enyaq 80x iV": {},
      "Enyaq 80x iV Coup\u00e9": {},
      "Enyaq RS iV": {},
      "Enyaq RS iV Coup\u00e9": {},
      "Enzo": {},
      "Eos": {},
      "Epica": {},
      "Escalade": {},
      "Escalade ESV": {},
      "Escalade ESV AWD": {},
      "Escalade ESV Turbo Diesel": {},
      "Escalade ESV Turbo Diesel AWD": {},
      "Escalade EXT": {},
      "Escalade Hybrid": {},
      "Escalade Sport Platinum AWD": {},
      "Escort IV": {},
      "Escort IV Cabrio": {},
      "Escort IV Kombi": {},
      "Escort IV RS": {},
      "1er Coup\u00e9": {
        "1998-2004": {
          "Continental Test Variant 10": [
            {
              "fitmentLabel": "215/65 R16",
              "width": 215,
              "aspectRatio": 65,
              "diameter": 16,
              "speedLoadIndex": "98V"
            }
          ]
        }
      }
    },
    "Jeep": {
      "Escort Sedan": {},
      "Escort V": {},
      "Escort V Cabrio": {},
      "Escort V RS": {},
      "Escort VI": {},
      "Escort VI Cabrio": {},
      "Escort VI Kombi": {},
      "Escort VI RS": {},
      "Escort VI RS 4X4": {},
      "Escort VII": {},
      "Escort VII 4X4": {},
      "Escort VII Cabrio": {},
      "Escort VII Cosworth": {},
      "Escort VII Kombi": {},
      "Escort VII RS": {},
      "Escort VII RS 4X4": {},
      "Escort VII XR3": {},
      "Escort Wagon": {},
      "Escort ZX2": {},
      "Escort ZX2 S/R": {},
      "Espace": {},
      "Espace II": {},
      "Espace III": {},
      "Espace IV": {},
      "Espace Quadra": {},
      "Espace V": {},
      "Espero": {},
      "Esprit": {},
      "Esprit GT1": {},
      "Esprit GT3": {},
      "Europa S": {},
      "Europa SE": {},
      "Evalia": {},
      "Evasion": {},
      "Evora": {},
      "Evora 400": {},
      "Evora 410": {},
      "Evora GT 410 Sport": {},
      "Evora GT 430": {},
      "Evora GT 430 Sport": {},
      "Evora GTE": {},
      "Evora S": {},
      "Exeo": {},
      "Exeo ST": {},
      "Exige": {},
      "1er Limousine": {
        "2005-2010": {
          "Continental Test Variant 11": [
            {
              "fitmentLabel": "225/40 R18",
              "width": 225,
              "aspectRatio": 40,
              "diameter": 18,
              "speedLoadIndex": "105V"
            }
          ]
        }
      }
    },
    "Kia": {
      "Exige Cup 380": {},
      "Exige Cup 430": {},
      "Exige Cup R": {},
      "Exige S": {},
      "Exige S RGB": {},
      "Exige Sport 380": {},
      "Exige Sport 410": {},
      "Expert Fourgon": {},
      "Expert Fourgon Nutzfahrzeug": {},
      "Expert Fourgon Tepee": {},
      "Explorer Sport Trac": {},
      "Explorer Sport Trac (2WD)": {},
      "Explorer Sport Trac Adrenalin": {},
      "Explorer Sport Trac Adrenalin (2WD)": {},
      "Express": {},
      "Extol": {},
      "F 355 Berlinetta": {},
      "F 355 Berlinetta F1": {},
      "F 355 GTS": {},
      "F 355 GTS F1": {},
      "F 355 Spider": {},
      "F 355 Spider F1": {},
      "F 40": {},
      "F 430": {},
      "F 430 Scuderia": {},
      "F 430 Spider": {},
      "F 50": {},
      "F 512 M": {},
      "F-250": {},
      "F-250 (2WD)": {},
      "F-250 XL": {},
      "F-250 XLT": {},
      "F-Pace": {},
      "F-Pace AWD": {},
      "F-Pace SVR": {},
      "F-Type": {},
      "F-Type AWD": {},
      "F-Type Coup\u00e9": {},
      "F-Type Coup\u00e9 AWD": {},
      "F-Type Coup\u00e9 R": {},
      "F-Type Coup\u00e9 R AWD": {},
      "F-Type Coup\u00e9 S": {},
      "F-Type Coup\u00e9 S AWD": {},
      "F-Type Coup\u00e9 SVR": {},
      "F-Type R": {},
      "1er M": {
        "2011-2016": {
          "Continental Test Variant 12": [
            {
              "fitmentLabel": "225/40 R18",
              "width": 225,
              "aspectRatio": 40,
              "diameter": 18,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      }
    },
    "Koenigsegg": {
      "F-Type R AWD": {},
      "F-Type S": {},
      "F-Type S AWD": {},
      "F-Type SVR": {},
      "F12 Berlinetta": {},
      "F12 TDF": {},
      "F8 Tributo": {},
      "FABIA RS": {},
      "FCX Clarity": {},
      "FF": {},
      "FJ Cruiser": {},
      "FJ Cruiser (2WD)": {},
      "FJ Cruiser Trail Teams": {},
      "FR Kizashi": {},
      "FR Kizashi Prestige": {},
      "FR Kizashi Sport AWD": {},
      "FR Kizashi Sport Prestige": {},
      "FR Kizashi Sport Touring": {},
      "FR Kizashi XL": {},
      "FR Kizashi XLS": {},
      "FR-V": {},
      "FX Vettel Edition": {},
      "FX30d": {},
      "FX35": {},
      "FX37": {},
      "FX50": {},
      "Fabia": {},
      "Fabia Combi": {},
      "Fabia II": {},
      "Fabia II Combi": {},
      "Fabia II Combi RS": {},
      "Fabia II RS": {},
      "Fabia III": {},
      "Fabia III Combi": {},
      "Fabia RS": {},
      "Fabia Sedan": {},
      "Favorit": {},
      "Favorit Kombi": {},
      "Felicia": {},
      "Felicia Kombi": {},
      "Feroza": {},
      "Fiesta III": {},
      "Fiesta III RS Turbo": {},
      "Fiesta III XR2": {},
      "Fiesta IV": {},
      "2": {
        "2017-2021": {
          "Continental Test Variant 1": [
            {
              "fitmentLabel": "225/40 R18",
              "width": 225,
              "aspectRatio": 40,
              "diameter": 18,
              "speedLoadIndex": "96H"
            }
          ]
        }
      }
    },
    "Ktm": {
      "Fiesta V": {},
      "Fiesta V ST 150": {},
      "Fiesta VI": {},
      "Fiesta VI Hatchback": {},
      "Fiesta VI ST": {},
      "Fiesta VI ST 200": {},
      "Fiesta VI Sedan": {},
      "Fiesta VII": {},
      "Fiesta VII ST 200": {},
      "Fiorino": {},
      "Fiorino III Combi": {},
      "Fiorino III Kleintransporter": {},
      "Flavia": {},
      "Fleetwood": {},
      "Fluence": {},
      "Fluence Z.E": {},
      "Flying Spur": {},
      "Flying Spur V8": {},
      "Flying Spur V8 S": {},
      "Flying Spur W12 S": {},
      "Focus": {},
      "Focus C-Max": {},
      "Focus CC": {},
      "Focus Elektrisch": {},
      "Focus II": {},
      "Focus II RS": {},
      "Focus II ST": {},
      "Focus II SW": {},
      "Focus II Sedan": {},
      "Focus III": {},
      "Focus III RS": {},
      "Focus III ST": {},
      "Focus III ST SW": {},
      "Focus III SW": {},
      "Focus III Sedan": {},
      "Focus IV": {},
      "Focus IV ST": {},
      "Focus IV SW": {},
      "Focus Kombi": {},
      "Focus RS": {},
      "Focus ST170": {},
      "Focus ST170 Kombi": {},
      "Focus Sedan": {},
      "ForFour": {},
      "ForFour Brabus": {},
      "2 Hybride": {
        "2022-2026": {
          "Continental Test Variant 2": [
            {
              "fitmentLabel": "225/40 R18",
              "width": 225,
              "aspectRatio": 40,
              "diameter": 18,
              "speedLoadIndex": "98V"
            }
          ]
        }
      }
    },
    "Lamborghini": {
      "ForFour Elektrisch Drive": {},
      "Forester": {},
      "Forester II": {},
      "Forester III": {},
      "Forester IV": {},
      "Forester e-Boxer": {},
      "Formentor": {},
      "Fortwo": {},
      "Fortwo Brabus": {},
      "Fortwo Brabus Elektrisch Drive": {},
      "Fortwo Cabrio": {},
      "Fortwo Cabrio Brabus": {},
      "Fortwo Cabrio Elektrisch Drive": {},
      "Fortwo Elektrisch Drive": {},
      "Fox": {},
      "Freeclimber": {},
      "Freeclimber 2": {},
      "Freeclimber 3": {},
      "Freeclimber Blue-lagon": {},
      "Freelander": {},
      "Freelander II": {},
      "Freemont": {},
      "Freemont 4X4": {},
      "Frontera": {},
      "Frontera Sport": {},
      "Fullback": {},
      "Fusion": {},
      "Fusion Energi Platinum": {},
      "Fusion Hybrid": {},
      "G 200": {},
      "G 230 kurz": {},
      "G 230 lang": {},
      "G 240": {},
      "G 240 kurz": {},
      "G 240 lang": {},
      "G 250 kurz": {},
      "G 250 lang": {},
      "G 270 kurz": {},
      "G 270 lang": {},
      "G 290 kurz": {},
      "G 290 lang": {},
      "G 300 kurz": {},
      "G 300 lang": {},
      "G 320 CDI kurz": {},
      "G 320 CDI lang": {},
      "200 CSR": {
        "1998-2004": {
          "Continental Test Variant 3": [
            {
              "fitmentLabel": "225/40 R19",
              "width": 225,
              "aspectRatio": 40,
              "diameter": 19,
              "speedLoadIndex": "105V"
            }
          ]
        }
      }
    },
    "Lancia": {
      "G 320 kurz": {},
      "G 320 lang": {},
      "G 350": {},
      "G 350 Bluetec lang": {},
      "G 350 d": {},
      "G 350 kurz": {},
      "G 350 lang": {},
      "G 400 d": {},
      "G 400 kurz": {},
      "G 400 lang": {},
      "G 500": {},
      "G 500 4x4\u00b2": {},
      "G 500 kurz": {},
      "G 500 lang": {},
      "G 55": {},
      "G 63": {},
      "G 63 6x6": {},
      "G 63 lang": {},
      "G 65 Landaulet Maybach": {},
      "G 65 lang": {},
      "G V12 800": {},
      "G lang": {},
      "G20": {},
      "G25": {},
      "G35": {},
      "G35 Coup\u00e9": {},
      "G37": {},
      "G37 CC": {},
      "G37 Coup\u00e9": {},
      "G80 EV II": {},
      "G80 II": {},
      "GL 320 CDI": {},
      "GL 350 BlueTec": {},
      "GL 350 CDI": {},
      "GL 400": {},
      "GL 420 CDI": {},
      "GL 450": {},
      "GL 450 CDI": {},
      "GL 500": {},
      "GL 63": {},
      "GL 63 Biturbo": {},
      "GLA 180": {},
      "GLA 180 CDI": {},
      "GLA 200": {},
      "GLA 200 CDI": {},
      "200 D": {
        "2005-2010": {
          "Continental Test Variant 4": [
            {
              "fitmentLabel": "225/40 R19",
              "width": 225,
              "aspectRatio": 40,
              "diameter": 19,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      }
    },
    "Land Rover": {
      "GLA 200 CDI 4Matic": {},
      "GLA 200 d": {},
      "GLA 200 d 4MATIC": {},
      "GLA 220 4MATIC": {},
      "GLA 220 CDI": {},
      "GLA 220 CDI 4Matic": {},
      "GLA 220 D": {},
      "GLA 220 D 4Matic": {},
      "GLA 250": {},
      "GLA 250 4Matic": {},
      "GLA 45 4Matic": {},
      "GLB 180 d": {},
      "GLB 200": {},
      "GLB 200 d": {},
      "GLB 200 d 4MATIC": {},
      "GLB 220d 4MATIC": {},
      "GLB 250 4MATIC": {},
      "GLC 200 4Matic": {},
      "GLC 200 D": {},
      "GLC 200 D Coup\u00e9": {},
      "GLC 220 D 4Matic": {},
      "GLC 220 D 4Matic Coup\u00e9": {},
      "GLC 220 D Coup\u00e9": {},
      "GLC 250 4Matic": {},
      "GLC 250 D 4Matic": {},
      "GLC 250 D 4Matic Coup\u00e9": {},
      "GLC 300 4Matic": {},
      "GLC 350 D 4Matic": {},
      "GLC 350 D 4Matic Coup\u00e9": {},
      "GLC 350 E 4Matic": {},
      "GLC 350 E 4Matic Coup\u00e9": {},
      "GLC 43 4Matic": {},
      "GLC 43 4Matic Coup\u00e9": {},
      "GLC 63 4Matic": {},
      "GLC 63 4Matic Coup\u00e9": {},
      "GLC 63 S 4Matic": {},
      "GLC 63 S 4Matic Coup\u00e9": {},
      "GLE 250 D": {},
      "GLE 250 D 4Matic": {},
      "GLE 300 D 4Matic": {},
      "GLE 350": {},
      "GLE 350 4MATIC": {},
      "GLE 350 D 4Matic": {},
      "GLE 350 D 4Matic Coup\u00e9": {},
      "GLE 400 4Matic": {},
      "200 E": {
        "2011-2016": {
          "Continental Test Variant 5": [
            {
              "fitmentLabel": "225/40 R19",
              "width": 225,
              "aspectRatio": 40,
              "diameter": 19,
              "speedLoadIndex": "98V"
            }
          ]
        }
      }
    },
    "Lexus": {
      "GLE 400 4Matic Coup\u00e9": {},
      "GLE 400 D 4Matic": {},
      "GLE 43 4Matic Coup\u00e9": {},
      "GLE 450 4Matic": {},
      "GLE 450 4Matic Coup\u00e9": {},
      "GLE 500 4Matic": {},
      "GLE 500 E 4Matic": {},
      "GLE 53 4MATIC+": {},
      "GLE 53 4MATIC+ Coup\u00e9": {},
      "GLE 580 4Matic": {},
      "GLE 63 4Matic": {},
      "GLE 63 4Matic Coup\u00e9": {},
      "GLE 63 S 4Matic": {},
      "GLE 63 S 4Matic Coup\u00e9": {},
      "GLK 200": {},
      "GLK 200 CDI": {},
      "GLK 220 BlueTec": {},
      "GLK 220 BlueTec 4Matic": {},
      "GLK 220 CDI": {},
      "GLK 220 CDI 4Matic": {},
      "GLK 250": {},
      "GLK 250 4Matic": {},
      "GLK 250 BlueTec": {},
      "GLK 250 BlueTec 4Matic": {},
      "GLK 250 CDI 4Matic": {},
      "GLK 280": {},
      "GLK 300 4Matic": {},
      "GLK 320 CDI": {},
      "GLK 350": {},
      "GLK 350 4Matic": {},
      "GLK 350 CDI 4Matic": {},
      "GLS 350 d 4Matic": {},
      "GLS 350d 4MATIC": {},
      "GLS 400 4Matic": {},
      "GLS 400 d 4Matic": {},
      "GLS 400d 4MATIC": {},
      "GLS 500": {},
      "GLS 550": {},
      "GLS 580 4Matic": {},
      "GLS 63": {},
      "GR Supra 3.0": {},
      "GR Supra 3.0 Premium": {},
      "GR Supra Launch Edition": {},
      "GR Yaris IV": {},
      "GS 200t": {},
      "200 Kombi": {
        "2017-2021": {
          "Continental Test Variant 6": [
            {
              "fitmentLabel": "225/45 R17",
              "width": 225,
              "aspectRatio": 45,
              "diameter": 17,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      }
    },
    "Ligier": {
      "GS 250": {},
      "GS 300": {},
      "GS 300h": {},
      "GS 350": {},
      "GS 430": {},
      "GS 450h": {},
      "GS 460": {},
      "GS F": {},
      "GT": {},
      "GT 4-T\u00fcren GT 43": {},
      "GT 4-T\u00fcren GT 43 4Matic +": {},
      "GT 4-T\u00fcren GT 53 4Matic +": {},
      "GT 4-T\u00fcren GT 63 4Matic +": {},
      "GT 4-T\u00fcren GT 63 S 4Matic +": {},
      "GT 86": {},
      "GT C": {},
      "GT C Roadster": {},
      "GT MF4": {},
      "GT MF4-S": {},
      "GT MF5": {},
      "GT R": {},
      "GT R Roadster": {},
      "GT Roadster": {},
      "GT S": {},
      "GT S MB 600": {},
      "GT S Roadster": {},
      "GT Turbo": {},
      "GT-R": {},
      "GT-R Nismo": {},
      "GTC4Lusso": {},
      "GTC4Lusso T": {},
      "GTV Coup\u00e9": {},
      "GTV6": {},
      "GV60": {},
      "GV70": {},
      "GV80": {},
      "Galant": {},
      "Galant 4X4": {},
      "Galaxy": {},
      "Galaxy AWD": {},
      "Gallardo": {},
      "Galloper": {},
      "Galloper II": {},
      "Genesis": {},
      "Genesis Coup\u00e9": {},
      "200 Quattro": {
        "2022-2026": {
          "Continental Test Variant 7": [
            {
              "fitmentLabel": "225/45 R17",
              "width": 225,
              "aspectRatio": 45,
              "diameter": 17,
              "speedLoadIndex": "91V"
            }
          ]
        }
      }
    },
    "Lincoln": {
      "Getz": {},
      "Ghibli": {},
      "Ghibli Diesel": {},
      "Ghibli GT": {},
      "Ghibli S": {},
      "Ghibli S Coup\u00e9": {},
      "Ghibli S Q4": {},
      "Ghost": {},
      "Ghost Black Badge": {},
      "Ghost Extended Wheelbase": {},
      "Giulia": {},
      "Giulia AWD": {},
      "Giulia Q4": {},
      "Giulia Quadrifoglio": {},
      "Giulia Spider 1300": {},
      "Giulia Sport": {},
      "Giulia Sport AWD": {},
      "Giulia Ti": {},
      "Giulia Ti AWD": {},
      "Giulia Ti Sport AWD": {},
      "Giulia Ti Sport Carbon": {},
      "Giulia Ti Sport Carbon AWD": {},
      "Giulia Veloce Q4": {},
      "Giulietta": {},
      "Giulietta - Quadrifoglio Verde": {},
      "Giulietta - Quadrifoglio Verde / Veloce": {},
      "Gladiator 80th Anniversary Diesel": {},
      "Gladiator Freedom Diesel": {},
      "Gladiator High Altitude Diesel": {},
      "Gladiator Overland": {},
      "Gladiator Overland Diesel": {},
      "Gladiator Rubicon": {},
      "Gladiator Rubicon Diesel": {},
      "Gladiator Sport": {},
      "Gladiator Sport S": {},
      "Gladiator Sport S Diesel": {},
      "Gladiator Willys Diesel": {},
      "Gladiator Willys Sport Diesel": {},
      "Golf": {},
      "Golf I GLi Cabrio": {},
      "Golf I GTi": {},
      "Golf I Oettinger": {},
      "Golf II": {},
      "Golf II Country": {},
      "Golf II G60": {},
      "200 SX (S13)": {
        "1998-2004": {
          "Continental Test Variant 8": [
            {
              "fitmentLabel": "225/45 R17",
              "width": 225,
              "aspectRatio": 45,
              "diameter": 17,
              "speedLoadIndex": "91W"
            }
          ]
        }
      }
    },
    "Lotus": {
      "Golf II GTi": {},
      "Golf II GTi 16S": {},
      "Golf II GTi 16S Edition One": {},
      "Golf II Match 16S": {},
      "Golf II Rallye": {},
      "Golf II Syncro": {},
      "Golf III": {},
      "Golf III Cabrio": {},
      "Golf III GT/GTi": {},
      "Golf III GTi 16S": {},
      "Golf III Syncro": {},
      "Golf III VR6": {},
      "Golf III VR6 Syncro": {},
      "Golf III Variant": {},
      "Golf III Variant Syncro": {},
      "Golf III Variant VR6 Syncro": {},
      "Golf IV": {},
      "Golf IV 4Motion": {},
      "Golf IV Cabrio": {},
      "Golf IV GTi 25th": {},
      "Golf IV R32": {},
      "Golf IV Variant": {},
      "Golf IV Variant 4Motion": {},
      "Golf V": {},
      "Golf V 4Motion": {},
      "Golf V GT": {},
      "Golf V GTD": {},
      "Golf V GTI Edition 30 / Pirelli": {},
      "Golf V GTi": {},
      "Golf V Plus": {},
      "Golf V R32": {},
      "Golf V Variant": {},
      "Golf V Variant 4Motion": {},
      "Golf VI": {},
      "Golf VI Cabrio": {},
      "Golf VI GTD": {},
      "Golf VI GTI": {},
      "Golf VI GTI Cabrio": {},
      "Golf VI GTI Edition 35": {},
      "Golf VI Plus": {},
      "Golf VI R": {},
      "Golf VI R Cabrio": {},
      "Golf VI Variant": {},
      "Golf VII": {},
      "Golf VII 4motion": {},
      "200 SX (S14)": {
        "2005-2010": {
          "Continental Test Variant 9": [
            {
              "fitmentLabel": "225/45 R17",
              "width": 225,
              "aspectRatio": 45,
              "diameter": 17,
              "speedLoadIndex": "94W"
            }
          ]
        }
      }
    },
    "Luxgen": {
      "Golf VII GTD": {},
      "Golf VII GTE": {},
      "Golf VII GTI": {},
      "Golf VII GTI Clubsport": {},
      "Golf VII GTI Clubsport S": {},
      "Golf VII GTI Performance": {},
      "Golf VII GTI TCR": {},
      "Golf VII R": {},
      "Golf VII SW": {},
      "Golf VII SW 4Motion": {},
      "Golf VII SW Alltrack": {},
      "Golf VII SW GTD": {},
      "Golf VII SW R": {},
      "Golf VII Sportsvan": {},
      "Golf VII e-Golf": {},
      "Golf VIII": {},
      "Gran Move": {},
      "GranCabrio": {},
      "GranCabrio MC": {},
      "GranCabrio Sport": {},
      "GranSport": {},
      "GranSport Spyder": {},
      "GranTurismo": {},
      "GranTurismo MC": {},
      "GranTurismo MC Stradale": {},
      "GranTurismo S": {},
      "GranTurismo Sport": {},
      "GranTurismo Sport Convertible": {},
      "Grand C-Max": {},
      "Grand C4 SpaceTourer": {},
      "Grand Cherokee": {},
      "Grand Cherokee 5.9 Limited": {},
      "Grand Cherokee 65th Anniversary": {},
      "Grand Cherokee Altitude": {},
      "Grand Cherokee High Altitude": {},
      "Grand Cherokee II": {},
      "Grand Cherokee III": {},
      "Grand Cherokee III SRT8": {},
      "Grand Cherokee IV": {},
      "Grand Cherokee IV SRT8": {},
      "Grand Cherokee IV Trackhawk": {},
      "Grand Cherokee Limited": {},
      "Grand Espace III": {},
      "Grand Espace IV": {},
      "Grand Kangoo II": {},
      "200 Vitesse": {
        "2011-2016": {
          "Continental Test Variant 10": [
            {
              "fitmentLabel": "225/45 R17",
              "width": 225,
              "aspectRatio": 45,
              "diameter": 17,
              "speedLoadIndex": "96H"
            }
          ]
        }
      }
    },
    "Man": {
      "Grand Modus": {},
      "Grand Santa Fe": {},
      "Grand Scenic II": {},
      "Grand Scenic III": {},
      "Grand Scenic IV": {},
      "Grand Scenic IV Hybrid Assist": {},
      "Grand Vitara": {},
      "Grand Vitara Cabrio": {},
      "Grand Vitara XL-7": {},
      "Grand Voyager": {},
      "Grand Voyager 4x4": {},
      "Grand Wagoneer": {},
      "Grandeur": {},
      "Grandis": {},
      "Grandland X": {},
      "Grecale GT": {},
      "Grecale Modena": {},
      "Griffith 500": {},
      "Guara Coup\u00e9": {},
      "H 100": {},
      "H-1 VAN": {},
      "H1": {},
      "H1 Alpha": {},
      "H2": {},
      "H2 SUT": {},
      "H3": {},
      "H3T": {},
      "HR-V 2WD": {},
      "HR-V 4WD": {},
      "HR-V AWD": {},
      "Hemera": {},
      "Hiace": {},
      "Hiace 4X4": {},
      "Highlander Hybrid": {},
      "Highlander LE (FWD)": {},
      "Hijet": {},
      "Hilux": {},
      "Hilux 2WD": {},
      "Hilux 4WD": {},
      "Huayra": {},
      "Huayra BC": {},
      "Huayra Roadster": {},
      "Huracan Evo": {},
      "Huracan Evo Spyder": {},
      "Huracan LP580-2": {},
      "2008": {
        "2017-2021": {
          "Continental Test Variant 11": [
            {
              "fitmentLabel": "225/50 R18",
              "width": 225,
              "aspectRatio": 50,
              "diameter": 18,
              "speedLoadIndex": "91H"
            }
          ]
        }
      }
    },
    "Marussia": {
      "Huracan LP610-4": {},
      "Huracan Performante  LP640-4": {},
      "Huracan Performante Spyder LP640-4": {},
      "Huracan Spyder LP580-2": {},
      "Huracan Spyder LP610-4": {},
      "I-PACE": {},
      "ID BUZZ CARGO": {},
      "ID BUZZ PRO": {},
      "ID.3 Pro": {},
      "ID.3 Pro Performance": {},
      "ID.3 Pro S": {},
      "ID.3 Pure Performance": {},
      "ID.4 GTX": {},
      "ID.4 Pro Performance": {},
      "ID.4 Pure": {},
      "ID.4 Pure Performance": {},
      "ID.5 GTX": {},
      "ID.5 Pro": {},
      "ID.5 Pro Performance": {},
      "IQ": {},
      "IS 200": {},
      "IS 200t": {},
      "IS 220d": {},
      "IS 250": {},
      "IS 250C": {},
      "IS 300": {},
      "IS 300 Sportcross": {},
      "IS 300C": {},
      "IS 300h": {},
      "IS 350": {},
      "IS F": {},
      "IX20": {},
      "IX35": {},
      "IX35 AWD": {},
      "IX35 Fuel Cell": {},
      "IX55": {},
      "Ibiza": {},
      "Ibiza Cupra": {},
      "Ibiza Cupra R": {},
      "Ibiza FR": {},
      "Ibiza SC": {},
      "Ibiza ST": {},
      "Idea": {},
      "Ignis": {},
      "Ignis 4x4": {},
      "2008 Crossway": {
        "2022-2026": {
          "Continental Test Variant 12": [
            {
              "fitmentLabel": "225/50 R18",
              "width": 225,
              "aspectRatio": 50,
              "diameter": 18,
              "speedLoadIndex": "94V"
            }
          ]
        }
      }
    },
    "Maserati": {
      "Ignis Allgrip": {},
      "Ignis Hybrid": {},
      "Ignis Hybrid Allgrip": {},
      "Iltis": {},
      "Impreza": {},
      "Impreza GT Turbo": {},
      "Impreza II": {},
      "Impreza II Kombi": {},
      "Impreza II WRX": {},
      "Impreza II WRX STI": {},
      "Impreza III": {},
      "Impreza III Kombi": {},
      "Impreza III WRX": {},
      "Impreza III WRX STI": {},
      "Impreza IV WRX STI": {},
      "Impreza V": {},
      "Impreza V Kombi": {},
      "Inca Combi": {},
      "Inca Combi & Van": {},
      "Inca Van": {},
      "Insight Coup\u00e9": {},
      "Insight Hybrid": {},
      "Insignia": {},
      "Insignia 4x4": {},
      "Insignia Country Tourer": {},
      "Insignia Country Tourer 4x4": {},
      "Insignia Grand Sport": {},
      "Insignia Grand Sport 4x4": {},
      "Insignia Grand Sport GSi": {},
      "Insignia OPC": {},
      "Insignia Sport Tourer": {},
      "Insignia Sport Tourer 4x4": {},
      "Insignia Sport Tourer OPC": {},
      "Insignia Sports Tourer": {},
      "Insignia Sports Tourer 4x4": {},
      "Insignia Sports Tourer GSI": {},
      "Integra Type R": {},
      "Interstar 2,8t": {},
      "Interstar 3,3t": {},
      "Interstar 3,5t": {},
      "Ioniq 5 EV": {},
      "Ioniq Elektrisch": {},
      "Ioniq Hybrid": {},
      "Ioniq Plug-in Hybrid": {},
      "JS50": {},
      "2008 II": {
        "1998-2004": {
          "Continental Test Variant 1": [
            {
              "fitmentLabel": "225/50 R18",
              "width": 225,
              "aspectRatio": 50,
              "diameter": 18,
              "speedLoadIndex": "98V"
            }
          ]
        }
      }
    },
    "Maybach": {
      "Jazz": {},
      "Jazz Hybrid": {},
      "Jesko": {},
      "Jetta": {},
      "Jetta 4X4": {},
      "Jetta GT": {},
      "Jetta Hybrid": {},
      "Jimny 2WD": {},
      "Jimny 4WD": {},
      "Jogger": {},
      "John Cooper Work Countryman": {},
      "John Cooper Works Clubman": {},
      "John Cooper Works Clubman All4": {},
      "John Cooper Works Countryman AWD": {},
      "John Cooper Works Countryman All4": {},
      "John Cooper Works Paceman All4": {},
      "Journey": {},
      "Juke": {},
      "Juke AWD": {},
      "Juke II": {},
      "Juke Nismo": {},
      "Juke Nismo AWD": {},
      "Juke Nismo RS": {},
      "Juke Nismo RS AWD": {},
      "Jumper Kombi 2t800": {},
      "Jumper Kombi 2t900": {},
      "Jumper Kombi 2t900 4X4": {},
      "Jumper Kombi 3t100 Camping Car": {},
      "Jumper Kombi 3t200": {},
      "Jumper Kombi 3t300": {},
      "Jumper Kombi 3t300 4X4": {},
      "Jumper Kombi 3t500": {},
      "Jumper Kombi 3t500 4X4": {},
      "Jumper Kombi 3t500 Camping Car": {},
      "Jumper Kombi Combi": {},
      "Jumper Kombi V.U": {},
      "Jumpy": {},
      "Jumpy Combi": {},
      "Jumpy V.U": {},
      "Jumpy V.U (L1H1 1000Kg)": {},
      "Justy I": {},
      "Justy II 2WD": {},
      "Justy II 4WD": {},
      "Justy III 4WD": {},
      "Justy IV 2WD": {},
      "205": {
        "2005-2010": {
          "Continental Test Variant 2": [
            {
              "fitmentLabel": "225/50 R18",
              "width": 225,
              "aspectRatio": 50,
              "diameter": 18,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      }
    },
    "Mazda": {
      "K 2500": {},
      "K 2700": {},
      "KUGA III": {},
      "Ka": {},
      "Ka+": {},
      "Kadett E": {},
      "Kadett E Cabrio": {},
      "Kadett E Cabrio GSI": {},
      "Kadett E Caravan": {},
      "Kadett E GSI": {},
      "Kadett E GT": {},
      "Kadjar": {},
      "Kadjar 4WD": {},
      "Kalos": {},
      "Kamiq": {},
      "Kangoo": {},
      "Kangoo (Erh\u00f6hte Nutzlast )": {},
      "Kangoo D\u00e9cathlon": {},
      "Kangoo Express": {},
      "Kangoo II": {},
      "Kangoo II (Access)": {},
      "Kangoo II (Tom Tom)": {},
      "Kangoo II (Tout Chemin)": {},
      "Kangoo II 4X4": {},
      "Kangoo II Automatik": {},
      "Kangoo II Express": {},
      "Kangoo II Express 4X4": {},
      "Kangoo II Express Z.E": {},
      "Kangoo RT": {},
      "Kangoo RTE": {},
      "Kappa": {},
      "Kappa Coup\u00e9": {},
      "Kappa Station Wagon": {},
      "Karl": {},
      "Karma": {},
      "Karoq": {},
      "Karoq 4x4": {},
      "Karoq 4x4 DSG7": {},
      "Kight": {},
      "King Cab Navara": {},
      "Kizashi Sport (4X2)": {},
      "Kizashi Sport (4X4)": {},
      "Kodiaq 4x2": {},
      "Kodiaq 4x4": {},
      "Kodiaq RS 4x4": {},
      "205 Cabrio": {
        "2011-2016": {
          "Continental Test Variant 3": [
            {
              "fitmentLabel": "225/55 R18",
              "width": 225,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "91H"
            }
          ]
        }
      }
    },
    "Mclaren": {
      "Koleos": {},
      "Koleos II 4X4": {},
      "Koleos II 4x2": {},
      "Kona": {},
      "Kona 4WD": {},
      "Kona Elektrisch": {},
      "Kona N": {},
      "Korando": {},
      "Korando 2WD": {},
      "Korando 4WD": {},
      "Korando e-Motion": {},
      "Kubistar": {},
      "Kuga 4X2": {},
      "Kuga 4X4": {},
      "Kuga II 4X2": {},
      "Kuga II 4X4": {},
      "Kyron": {},
      "L 200": {},
      "L 200 2WD": {},
      "L 200 4WD": {},
      "LC 500": {},
      "LC 500h": {},
      "LFA": {},
      "LP 560-2": {},
      "LP 560-2 Spyder": {},
      "LP 560-4": {},
      "LP 560-4 Spyder": {},
      "LP 570-4 Spyder Performante": {},
      "LP 570-4 Superleggera": {},
      "LS": {},
      "LS 400": {},
      "LS 430": {},
      "LS 460": {},
      "LS 460 4WD": {},
      "LS 500 4WD": {},
      "LS 500h 2WD": {},
      "LS 500h 4WD": {},
      "LS 600h": {},
      "LS 600h L": {},
      "LS sport Package": {},
      "LT 28": {},
      "LT 31": {},
      "LT 32": {},
      "LT 35": {},
      "LT 35 Z": {},
      "205 GT": {
        "2017-2021": {
          "Continental Test Variant 4": [
            {
              "fitmentLabel": "225/55 R18",
              "width": 225,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "91V"
            }
          ]
        }
      }
    },
    "Mercedes": {
      "LT 40": {},
      "LT 46": {},
      "LaFerrari": {},
      "LaFerrari Aperta": {},
      "Lacetti": {},
      "Lagonda Taraf": {},
      "Laguna": {},
      "Laguna Coup\u00e9": {},
      "Laguna II": {},
      "Laguna II Estate": {},
      "Laguna II Estate GT": {},
      "Laguna II GT": {},
      "Laguna III": {},
      "Laguna III Estate": {},
      "Laguna III Estate GT 4control": {},
      "Laguna III GT": {},
      "Laguna III GT 4control": {},
      "Laguna Nevada": {},
      "Lancer": {},
      "Lancer 4WD": {},
      "Lancer Evolution IX": {},
      "Lancer Evolution V": {},
      "Lancer Evolution VI": {},
      "Lancer Evolution VII": {},
      "Lancer Evolution VIII": {},
      "Lancer Evolution X": {},
      "Lancer Fortis": {},
      "Lancer Kombi": {},
      "Lancer Ralliart": {},
      "Land 109": {},
      "Land 110": {},
      "Land 88": {},
      "Land 90": {},
      "Land Cruiser": {},
      "Land Cruiser (J12)": {},
      "Land Cruiser (J70)": {},
      "Land Cruiser 100 (J10)": {},
      "Land Cruiser 150": {},
      "Land Cruiser 200 (J20)": {},
      "Land Cruiser 80": {},
      "Land Cruiser 90": {},
      "Land Cruiser Station Wagon (J10)": {},
      "Land Cruiser Station Wagon (J12)": {},
      "Land Cruiser Station Wagon 200 (J20)": {},
      "Land Cruiser World Cup": {},
      "205 GTI": {
        "2022-2026": {
          "Continental Test Variant 5": [
            {
              "fitmentLabel": "225/55 R18",
              "width": 225,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "94W"
            }
          ]
        }
      }
    },
    "Mercedes Amg": {
      "Lanos": {},
      "Lantra": {},
      "Lantra II": {},
      "Lantra II Kombi": {},
      "Latitude": {},
      "Le Baron": {},
      "Le Baronron": {},
      "Leaf": {},
      "Leaf II": {},
      "Legacy": {},
      "Legacy II": {},
      "Legacy II Kombi": {},
      "Legacy III": {},
      "Legacy III Kombi": {},
      "Legacy IV": {},
      "Legacy IV GT Spec B": {},
      "Legacy IV Kombi": {},
      "Legacy Kombi": {},
      "Legacy Outback": {},
      "Legacy V": {},
      "Legacy V SW": {},
      "Legacy VI": {},
      "Leganza": {},
      "Legend": {},
      "Legend Coup\u00e9": {},
      "Leon": {},
      "Leon 4X4": {},
      "Leon Cupra R": {},
      "Leon Cupra V6": {},
      "Leon II": {},
      "Leon II Cupra": {},
      "Leon II Cupra R": {},
      "Leon II FR": {},
      "Leon III": {},
      "Leon III Cupra": {},
      "Leon III Cupra R": {},
      "Leon III FR": {},
      "Leon III SC": {},
      "Leon III SC Cupra": {},
      "Leon III SC FR": {},
      "Leon III ST": {},
      "Leon III ST Cupra": {},
      "Leon III ST Cupra 4Drive": {},
      "Leon III ST FR": {},
      "Leon III X-Perience": {},
      "205 Gentry": {
        "1998-2004": {
          "Continental Test Variant 6": [
            {
              "fitmentLabel": "225/55 R18",
              "width": 225,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "98V"
            }
          ]
        }
      }
    },
    "Mg": {
      "Leon III X-Perience 4Drive": {},
      "Leon IV": {},
      "Leon IV ST": {},
      "Levante": {},
      "Levante Diesel": {},
      "Levante S": {},
      "Levante Trofeo": {},
      "Levorg": {},
      "Liana": {},
      "Liberty": {},
      "Liberty (2WD)": {},
      "Liberty (4X2)": {},
      "Liberty (4X4)": {},
      "Liberty Limited": {},
      "Liberty Limited (2WD)": {},
      "Liberty Renegade": {},
      "Linea": {},
      "LiteAce": {},
      "Lodgy": {},
      "Lodgy Stepway": {},
      "Logan": {},
      "Logan II": {},
      "Logan III": {},
      "Logan MCV": {},
      "Logan Pick Up": {},
      "Logan VAN": {},
      "Logo": {},
      "Lupo": {},
      "Lupo GTI": {},
      "Lybra": {},
      "Lybra Sportwagon": {},
      "M25": {},
      "M30d": {},
      "M35": {},
      "M35h": {},
      "M4": {},
      "M45": {},
      "MC20": {},
      "MF3": {},
      "MF3 Final Edition": {},
      "MG F": {},
      "MG F Cabrio": {},
      "MG TF": {},
      "MG V8 Cabrio": {},
      "MG ZR": {},
      "205 Rallye": {
        "2005-2010": {
          "Continental Test Variant 7": [
            {
              "fitmentLabel": "225/55 R18",
              "width": 225,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      }
    },
    "Mg Rover": {
      "MG ZS": {},
      "MG ZT": {},
      "MG ZT-T": {},
      "MGO": {},
      "MGO Highland": {},
      "MKC": {},
      "MKS": {},
      "MKS AWD": {},
      "MKT": {},
      "MKT AWD": {},
      "MKX": {},
      "MKX AWD": {},
      "MKX AWD Sport": {},
      "MKZ": {},
      "MKZ AWD": {},
      "MKZ Hybrid": {},
      "MKZ Reserve II AWD": {},
      "ML 230": {},
      "ML 250 BlueTEC": {},
      "ML 270 CDI": {},
      "ML 280 CDI": {},
      "ML 300 CDI": {},
      "ML 320": {},
      "ML 320 CDI": {},
      "ML 350": {},
      "ML 350 BlueEFFICIENCY": {},
      "ML 350 Bluetec": {},
      "ML 350 Bluetec CDI": {},
      "ML 350 CDI": {},
      "ML 400": {},
      "ML 400 CDI": {},
      "ML 430": {},
      "ML 450 CDI": {},
      "ML 500": {},
      "ML 55": {},
      "ML 63": {},
      "ML D8 S": {},
      "MP4-12C": {},
      "MP4-12C Spyder": {},
      "MPV": {},
      "MR (MK II)": {},
      "MR-S (MK III)": {},
      "MSO HS": {},
      "MX-30": {},
      "MX3": {},
      "205 van": {
        "2011-2016": {
          "Continental Test Variant 8": [
            {
              "fitmentLabel": "235/35 R19",
              "width": 235,
              "aspectRatio": 35,
              "diameter": 19,
              "speedLoadIndex": "91H"
            }
          ]
        }
      }
    },
    "Mia Elektrisch": {
      "MX5 NA": {},
      "MX5 NB": {},
      "MX5 NC": {},
      "MX5 ND": {},
      "MX5 ND RF": {},
      "MX6": {},
      "Mac 500": {},
      "Macan": {},
      "Macan GTS": {},
      "Macan S": {},
      "Macan S Diesel": {},
      "Macan Turbo": {},
      "Macan Turbo Performance": {},
      "Mach-E": {},
      "Mach-E AWD": {},
      "Maestro": {},
      "Magentis": {},
      "Malaga": {},
      "Malibu": {},
      "Malibu L": {},
      "Marbella": {},
      "Marco Polo 160 D Activity": {},
      "Marco Polo 180 D Activity": {},
      "Marco Polo 200 D": {},
      "Marco Polo 200 D Activity": {},
      "Marco Polo 220 D": {},
      "Marco Polo 220 D 4Matic": {},
      "Marco Polo 220 D Activity": {},
      "Marco Polo 250 D": {},
      "Marco Polo 250 D 4Matic": {},
      "Marco Polo 250 D Activity": {},
      "Marea": {},
      "Marea Week-end": {},
      "Master I 2t800": {},
      "Master I 3t200": {},
      "Master I 3t300": {},
      "Master I 3t500": {},
      "Master I 3t900": {},
      "Master I Minibus": {},
      "Master II VU": {},
      "Master Z.E": {},
      "Materia": {},
      "Matiz": {},
      "Matrix": {},
      "Maverick kurz": {},
      "206": {
        "2017-2021": {
          "Continental Test Variant 9": [
            {
              "fitmentLabel": "235/35 R19",
              "width": 235,
              "aspectRatio": 35,
              "diameter": 19,
              "speedLoadIndex": "94V"
            }
          ]
        }
      }
    },
    "Microcar": {
      "Maverick lang": {},
      "Maxity": {},
      "Maxity Elektrisch": {},
      "Maybach 57": {},
      "Maybach 57 Zeppelin": {},
      "Maybach 62": {},
      "Maybach 62 Zeppelin": {},
      "Maybach Landaulet": {},
      "Megane": {},
      "Megane Cabrio": {},
      "Megane Classic": {},
      "Megane Coup\u00e9": {},
      "Megane E-Tech 100% electric": {},
      "Megane II": {},
      "Megane II CC": {},
      "Megane II Estate": {},
      "Megane II Limousine 4-T\u00fcren": {},
      "Megane II RS": {},
      "Megane II RS Energy": {},
      "Megane II RS F1 Team": {},
      "Megane II RS R26": {},
      "Megane II RS R26-R": {},
      "Megane II RS Trophy": {},
      "Megane III": {},
      "Megane III CC": {},
      "Megane III CC GT": {},
      "Megane III Coup\u00e9": {},
      "Megane III Coup\u00e9 GT": {},
      "Megane III Estate": {},
      "Megane III Estate GT": {},
      "Megane III GT": {},
      "Megane III RS": {},
      "Megane III RS 275 Trophy": {},
      "Megane III RS Trophy": {},
      "Megane IV": {},
      "Megane IV GT": {},
      "Megane IV GT Estate": {},
      "Megane IV Grandtour": {},
      "Megane IV RS": {},
      "Megane IV RS Trophy": {},
      "Megane IV RS Trophy-R": {},
      "Megane Kombi": {},
      "Merit": {},
      "Meriva": {},
      "Metro": {},
      "206 +": {
        "2022-2026": {
          "Continental Test Variant 10": [
            {
              "fitmentLabel": "235/35 R19",
              "width": 235,
              "aspectRatio": 35,
              "diameter": 19,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      }
    },
    "Mini": {
      "Mia": {},
      "Mia U": {},
      "Micra": {},
      "Micra C+C": {},
      "Mii": {},
      "Mii Electric": {},
      "Mini": {},
      "Mini Cabrio": {},
      "Mini Cooper": {},
      "Mini Cooper Cabrio": {},
      "Mini Cooper Cabrio Sidewalk": {},
      "Mini Cooper Coup\u00e9": {},
      "Mini Cooper D": {},
      "Mini Cooper D Cabrio": {},
      "Mini Cooper Hardtop": {},
      "Mini Cooper Roadster": {},
      "Mini Cooper S": {},
      "Mini Cooper S Cabrio": {},
      "Mini Cooper S Cabrio Sidewalk": {},
      "Mini Cooper S Coup\u00e9": {},
      "Mini Cooper S John Cooper Works": {},
      "Mini Cooper S Roadster": {},
      "Mini Cooper SD": {},
      "Mini Cooper SD Cabrio": {},
      "Mini Cooper SD Coup\u00e9": {},
      "Mini Cooper SD Roadster": {},
      "Mini Cooper SE": {},
      "Mini John Cooper Works": {},
      "Mini John Cooper Works Cabrio": {},
      "Mini John Cooper Works Coup\u00e9": {},
      "Mini John Cooper Works GP": {},
      "Mini John Cooper Works GP II": {},
      "Mini John Cooper Works Roadster": {},
      "Mini Mum": {},
      "Mini One": {},
      "Mini One Cabrio": {},
      "Mini One Cabrio Sidewalk": {},
      "Mini One D": {},
      "Mirai": {},
      "Mito": {},
      "Mito - Quadrifoglio Verde": {},
      "Model 3 Performance": {},
      "Model 3 Standard": {},
      "Model 3 lang Range": {},
      "Model S - 60": {},
      "206 CC": {
        "1998-2004": {
          "Continental Test Variant 11": [
            {
              "fitmentLabel": "235/40 R18",
              "width": 235,
              "aspectRatio": 40,
              "diameter": 18,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      }
    },
    "Mitsubishi": {
      "Model S - 70": {},
      "Model S - 70D": {},
      "Model S - 75D": {},
      "Model S - 85": {},
      "Model S - 85D": {},
      "Model S - 90D": {},
      "Model S - P100D": {},
      "Model S - P85D": {},
      "Model S - P90D": {},
      "Model X 100D": {},
      "Model X 75D": {},
      "Model X 90D": {},
      "Model Y Long Range": {},
      "Model Y Performance": {},
      "Modell F": {},
      "Modell F 4X4": {},
      "Modus": {},
      "Mokka 4X2": {},
      "Mokka 4X4": {},
      "Mokka II": {},
      "Mokka X 4X2": {},
      "Mokka X 4X4": {},
      "Mokka-e II": {},
      "Mondeo": {},
      "Mondeo 4X4": {},
      "Mondeo 4X4 Kombi": {},
      "Mondeo II": {},
      "Mondeo II Kombi": {},
      "Mondeo II ST200": {},
      "Mondeo III": {},
      "Mondeo III Kombi": {},
      "Mondeo III Kombi ST220": {},
      "Mondeo III ST220": {},
      "Mondeo IV": {},
      "Mondeo IV SW": {},
      "Mondeo IV Sedan": {},
      "Mondeo Kombi": {},
      "Mondeo V": {},
      "Mondeo V AWD": {},
      "Mondeo V SW": {},
      "Mondeo V SW AWD": {},
      "Mondeo V SW Vignale": {},
      "Mondeo V Vignale": {},
      "Mondial": {},
      "Mondial Cabrio": {},
      "206 GT": {
        "2005-2010": {
          "Continental Test Variant 12": [
            {
              "fitmentLabel": "235/40 R18",
              "width": 235,
              "aspectRatio": 40,
              "diameter": 18,
              "speedLoadIndex": "91V"
            }
          ]
        }
      }
    },
    "Mitsubishi Fuso": {
      "Montego": {},
      "Montego Clubman": {},
      "Montego L": {},
      "Montego LX": {},
      "Montego SL": {},
      "Montego Tourer": {},
      "Montego Tourer Clubman": {},
      "Monterey": {},
      "Monza SP1": {},
      "Monza SP2": {},
      "Movano 2t800": {},
      "Movano 3t300": {},
      "Movano 3t500": {},
      "Movano II VU": {},
      "Move": {},
      "Mulsanne": {},
      "Mulsanne Extended Wheelbase": {},
      "Mulsanne Speed": {},
      "Multipla": {},
      "Multivan": {},
      "Multivan 4Motion": {},
      "Murano": {},
      "Murano Cross Cabrio": {},
      "Murcielago": {},
      "Murcielago Roadster": {},
      "Musa": {},
      "Musso": {},
      "Musso Pick-up": {},
      "Musso Sports": {},
      "Mustang": {},
      "Mustang Bullitt": {},
      "Mustang Cabrio": {},
      "Mustang Cobra": {},
      "Mustang Cobra Cabrio": {},
      "Mustang Cobra Convertible": {},
      "Mustang Cobra R": {},
      "Mustang EcoBoost": {},
      "Mustang EcoBoost Premium": {},
      "Mustang GT": {},
      "Mustang GT Cabrio": {},
      "Mustang GT Performance Package": {},
      "Mustang GT Performance Package Level 2": {},
      "Mustang GT Premium": {},
      "Mustang GT500": {},
      "Mustang Mach 1": {},
      "206 RC": {
        "2011-2016": {
          "Continental Test Variant 1": [
            {
              "fitmentLabel": "235/40 R18",
              "width": 235,
              "aspectRatio": 40,
              "diameter": 18,
              "speedLoadIndex": "94W"
            }
          ]
        }
      }
    },
    "Morgan": {
      "Mustang SVT Cobra": {},
      "Mustang SVT Cobra R": {},
      "Mustang Shelby GT": {},
      "Mustang Shelby GT 500": {},
      "Mustang Shelby GT350": {},
      "Mustang Shelby GT350R": {},
      "NP300": {},
      "NSX Coup\u00e9": {},
      "NSX II": {},
      "NV1500": {},
      "NV200": {},
      "NV250": {},
      "NV300": {},
      "NV400 VU": {},
      "NX 200t": {},
      "NX 300 2WD": {},
      "NX 300 4WD": {},
      "NX 300h": {},
      "NX 300h 2WD": {},
      "Navara": {},
      "Navara 4X2": {},
      "Navara 4X4": {},
      "Navara AT32": {},
      "Navigator": {},
      "Navigator L": {},
      "Nemo Kombi": {},
      "Nemo Kombi Kleintransporter": {},
      "Neon": {},
      "New Beetle": {},
      "New Beetle Cabrio": {},
      "New Yorker": {},
      "Nexia": {},
      "Nexo": {},
      "Niro": {},
      "Nitro (4X2)": {},
      "Nitro (4X4)": {},
      "Note": {},
      "Note II": {},
      "Nubira": {},
      "Nubira Kombi": {},
      "Nubira SW": {},
      "Octavia": {},
      "Octavia  Combi": {},
      "Octavia 4X4": {},
      "Octavia Combi": {},
      "206 S16": {
        "2017-2021": {
          "Continental Test Variant 2": [
            {
              "fitmentLabel": "235/40 R18",
              "width": 235,
              "aspectRatio": 40,
              "diameter": 18,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      }
    },
    "Nissan": {
      "Octavia Combi 4X4": {},
      "Octavia Combi RS": {},
      "Octavia Combi RS 4X4": {},
      "Octavia G-TEC": {},
      "Octavia G-TEC Combi": {},
      "Octavia RS": {},
      "Octavia RS 4WD": {},
      "Octavia RS Combi": {},
      "Octavia Scout": {},
      "Omega": {},
      "Omega Kombi": {},
      "Omega Lotus": {},
      "Omega MV6": {},
      "One 77": {},
      "One Clubman": {},
      "One Countryman": {},
      "One D Clubman": {},
      "One D Countryman": {},
      "One:1": {},
      "Opirus": {},
      "Optima": {},
      "Optima  SW": {},
      "Optima Hybrid": {},
      "Optima SW": {},
      "Optima SW Hybrid": {},
      "Optra": {},
      "Orlando": {},
      "Outlander": {},
      "Outlander 2WD": {},
      "Outlander ES": {},
      "Outlander GT 3.0": {},
      "Outlander LE": {},
      "Outlander Limited Edition": {},
      "Outlander PHEV": {},
      "Outlander SE": {},
      "Outlander SEL": {},
      "P1": {},
      "PT Cruiser": {},
      "PT Cruiser Cabrio": {},
      "Pajero": {},
      "Pajero II": {},
      "Pajero III": {},
      "Pajero IV": {},
      "Pajero Pinin": {},
      "Pajero Sport": {},
      "206 SW": {
        "2022-2026": {
          "Continental Test Variant 3": [
            {
              "fitmentLabel": "235/40 R19",
              "width": 235,
              "aspectRatio": 40,
              "diameter": 19,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      }
    },
    "Opel": {
      "Palio": {},
      "Palio II": {},
      "Palio Week End": {},
      "Panamera": {},
      "Panamera 4": {},
      "Panamera 4 E-Hybrid": {},
      "Panamera 4 Sport Turismo": {},
      "Panamera 4S": {},
      "Panamera 4S Diesel": {},
      "Panamera 4S Sport Turismo": {},
      "Panamera Diesel": {},
      "Panamera GTS": {},
      "Panamera GTS Sport Turismo": {},
      "Panamera S": {},
      "Panamera S E-Hybrid": {},
      "Panamera S Hybrid": {},
      "Panamera Sport Turismo": {},
      "Panamera Sport Turismo 4 E-Hybrid": {},
      "Panamera Sport Turismo 4S Diesel": {},
      "Panamera Sport Turismo Turbo": {},
      "Panamera Sport Turismo Turbo S E-Hybrid": {},
      "Panamera Turbo": {},
      "Panamera Turbo S": {},
      "Panamera Turbo S E-Hybrid": {},
      "Panda I": {},
      "Panda I 4X4": {},
      "Panda II": {},
      "Panda II 4X4": {},
      "Panda III": {},
      "Panda III 4X4": {},
      "Panda III Cross": {},
      "Pantera Coup\u00e9": {},
      "Park Avenue": {},
      "Park Avenue Ultra": {},
      "Partner Fourgon Combi 650 kg": {},
      "Partner Fourgon Combispace": {},
      "Partner Fourgon Combispace 4X4": {},
      "Partner Fourgon Combispace 4X4 Dangel": {},
      "Partner Fourgon Combispace Ushua\u00efa": {},
      "Partner Fourgon Elektrisch": {},
      "Partner Fourgon II V.U": {},
      "Partner Fourgon II V.U Baustelle": {},
      "Partner Fourgon II V.U Elektrisch": {},
      "Partner Fourgon III": {},
      "Partner Fourgon Kleintransporter Nutzlast 475 kg": {},
      "206 SW S16": {
        "1998-2004": {
          "Continental Test Variant 4": [
            {
              "fitmentLabel": "235/40 R19",
              "width": 235,
              "aspectRatio": 40,
              "diameter": 19,
              "speedLoadIndex": "91V"
            }
          ]
        }
      }
    },
    "Pagani": {
      "Partner Fourgon Kleintransporter Nutzlast 600 Kg": {},
      "Partner Fourgon Kleintransporter Nutzlast 800 Kg": {},
      "Partner Fourgon tepee": {},
      "Paseo": {},
      "Paseo Convertible": {},
      "Paseo Coup\u00e9": {},
      "Passat": {},
      "Passat 4Motion": {},
      "Passat 4X4": {},
      "Passat Alltrack": {},
      "Passat Alltrack 4Motion": {},
      "Passat CC": {},
      "Passat CC 4 MOTION": {},
      "Passat GT": {},
      "Passat GTE": {},
      "Passat R36": {},
      "Passat SW": {},
      "Passat SW 4Motion": {},
      "Passat SW GTE": {},
      "Passat Variant": {},
      "Passat Variant 4Motion": {},
      "Passat Variant 4X4": {},
      "Passat Variant 4X4 G60": {},
      "Passat Variant R36": {},
      "Pathfinder": {},
      "Pathfinder (2WD)": {},
      "Patriot": {},
      "Patrol": {},
      "Patrol GR": {},
      "Patrol Pick-Up": {},
      "Phaeton": {},
      "Phantom": {},
      "Phantom Coup\u00e9": {},
      "Phantom Drophead": {},
      "Phantom Extended Wheelbase": {},
      "Phedra": {},
      "Picanto": {},
      "Pick Up": {},
      "Picnic": {},
      "Pixo": {},
      "Plus 4": {},
      "Plus 6": {},
      "Polestar 1": {},
      "Polestar 2": {},
      "Polo Classic": {},
      "206 Sedan": {
        "2005-2010": {
          "Continental Test Variant 5": [
            {
              "fitmentLabel": "235/40 R19",
              "width": 235,
              "aspectRatio": 40,
              "diameter": 19,
              "speedLoadIndex": "94W"
            }
          ]
        }
      }
    },
    "Peugeot": {
      "Polo Coup\u00e9": {},
      "Polo Coup\u00e9 GT": {},
      "Polo Fun": {},
      "Polo II": {},
      "Polo II G40": {},
      "Polo III": {},
      "Polo IV": {},
      "Polo IV GTI": {},
      "Polo V": {},
      "Polo V Blue GT": {},
      "Polo V GTI": {},
      "Polo V R WRC": {},
      "Polo VI": {},
      "Polo VI GTI": {},
      "Polo Variant": {},
      "Pony": {},
      "Porter": {},
      "Porter EL": {},
      "Porter Maxxi": {},
      "Portofino": {},
      "Prairie": {},
      "Prairie 4X4": {},
      "Pregio": {},
      "Prelude IV": {},
      "Prelude IV 4WD": {},
      "Prelude V": {},
      "Prelude V 4WD": {},
      "Prelude V Automatik": {},
      "Prelude V Coup\u00e9": {},
      "Premacy": {},
      "Previa": {},
      "Pride": {},
      "Primastar 2,7t": {},
      "Primastar 2,9t": {},
      "Primera": {},
      "Primera Kombi": {},
      "Prisma": {},
      "Prius": {},
      "Prius Five": {},
      "Prius Four": {},
      "Prius Plus": {},
      "Prius Prime": {},
      "Pro Cee'd": {},
      "Pro Cee'd GT": {},
      "ProCeed": {},
      "207": {
        "2011-2016": {
          "Continental Test Variant 6": [
            {
              "fitmentLabel": "235/45 R18",
              "width": 235,
              "aspectRatio": 45,
              "diameter": 18,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      }
    },
    "Pgo": {
      "Proace": {},
      "Proace City": {},
      "Proace City Verso": {},
      "Proace II": {},
      "Proace II Verso": {},
      "Probe": {},
      "Pulsar": {},
      "Pulsar GT": {},
      "Puma": {},
      "Punto": {},
      "Punto Abarth": {},
      "Punto Cabrio": {},
      "Punto Evo": {},
      "Punto Evo Supersport": {},
      "Punto GT Turbo": {},
      "Punto Grande": {},
      "Punto Kombi": {},
      "Punto Sporting": {},
      "Punto Super Sport": {},
      "Q2": {},
      "Q2 Quattro": {},
      "Q3": {},
      "Q3 Sportback": {},
      "Q3 Sportback Quattro": {},
      "Q30": {},
      "Q30 AWD": {},
      "Q4 35 Sportback e-tron": {},
      "Q4 35 e-tron": {},
      "Q4 40 Sportback e-tron": {},
      "Q4 40 e-tron": {},
      "Q4 45 Sportback e-tron quattro": {},
      "Q4 45 e-tron quattro": {},
      "Q4 50 Sportback e-tron quattro": {},
      "Q4 50 e-tron quattro": {},
      "Q5": {},
      "Q5 Hybrid": {},
      "Q5 Quattro": {},
      "Q5 Sportback Quattro 40 TDI 204": {},
      "Q5 Sportback Quattro 45 TFSI 265": {},
      "Q5 Sportback Quattro 50 TDI 286": {},
      "Q5 Sportback Quattro 50 TFSI e 299": {},
      "Q5 Sportback Quattro 55 TFSI e 367": {},
      "Q50": {},
      "Q50 Hybrid": {},
      "Q50 Hybrid (AWD)": {},
      "207 +": {
        "2017-2021": {
          "Continental Test Variant 7": [
            {
              "fitmentLabel": "235/45 R18",
              "width": 235,
              "aspectRatio": 45,
              "diameter": 18,
              "speedLoadIndex": "105V"
            }
          ]
        }
      }
    },
    "Piaggio": {
      "Q50 S": {},
      "Q60 Cabrio": {},
      "Q60 Coup\u00e9": {},
      "Q60 S Coup\u00e9": {},
      "Q7": {},
      "Q7 Quattro": {},
      "Q7 e-tron": {},
      "Q70": {},
      "Q70 Hybrid": {},
      "Q8 Quattro": {},
      "QX30": {},
      "QX50": {},
      "QX70": {},
      "Qashqai": {},
      "Qashqai +2": {},
      "Qashqai +2 All-Mode": {},
      "Qashqai 4x4": {},
      "Qashqai All-Mode": {},
      "Quargo": {},
      "Quattro": {},
      "Quattroporte": {},
      "Quattroporte Diesel": {},
      "Quattroporte GTS": {},
      "Quattroporte S": {},
      "Quattroporte S Q4": {},
      "Quattroporte Sport GTS": {},
      "Qubo": {},
      "R 280 CDI": {},
      "R 300": {},
      "R 300 CDI": {},
      "R 320 CDI": {},
      "R 350": {},
      "R 350 CDI": {},
      "R 350 CDI Bluetec": {},
      "R 500": {},
      "R 63": {},
      "R11 Turbo GRPE A": {},
      "R19": {},
      "R19 16S": {},
      "R19 16S Cabrio": {},
      "R19 Cabrio": {},
      "R19 Chamade": {},
      "R21": {},
      "R21 4X4": {},
      "R21 Nevada": {},
      "207 CC": {
        "2022-2026": {
          "Continental Test Variant 8": [
            {
              "fitmentLabel": "235/45 R18",
              "width": 235,
              "aspectRatio": 45,
              "diameter": 18,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      }
    },
    "Polaris": {
      "R21 Nevada 4X4": {},
      "R21 Turbo": {},
      "R21 Turbo 4X4": {},
      "R25": {},
      "R25 V6 Turbo Baccara": {},
      "R4": {},
      "R5": {},
      "R5 Alpine Turbo": {},
      "R8": {},
      "R8 GT": {},
      "R8 GT Spyder": {},
      "R8 II E-Tron": {},
      "R8 II V10": {},
      "R8 II V10 Decennium": {},
      "R8 II V10 Performance": {},
      "R8 II V10 Plus": {},
      "R8 II V10 RWS": {},
      "R8 II V10 RWS Spyder": {},
      "R8 II V10 Spyder": {},
      "R8 Spyder": {},
      "R8 V10": {},
      "R8 V10 LMX": {},
      "R8 V10 Plus": {},
      "R8 V10 Spyder": {},
      "RAV 4": {},
      "RAV 4 II": {},
      "RAV 4 III": {},
      "RAV 4 IV (2WD)": {},
      "RAV 4 IV (4WD)": {},
      "RAV 4 LE Hybrid (AWD)": {},
      "RAV 4 LIMITED (AWD)": {},
      "RAV 4 LIMITED (FWD)": {},
      "RAV 4 LIMITED Hybrid (AWD)": {},
      "RAV 4 TRD Off-Road": {},
      "RAV 4 V (2WD)": {},
      "RAV 4 V (4WD)": {},
      "RAV 4 XLE (AWD)": {},
      "RAV 4 XLE (FWD)": {},
      "RAV 4 XLE Hybrid (AWD)": {},
      "RAV 4 XLE Premium (AWD)": {},
      "RAV 4 XLE Premium (FWD)": {},
      "RAV 4 XSE Hybrid (AWD)": {},
      "RC 200t": {},
      "RC 300h": {},
      "RC 350": {},
      "207 RC": {
        "1998-2004": {
          "Continental Test Variant 9": [
            {
              "fitmentLabel": "235/45 R18",
              "width": 235,
              "aspectRatio": 45,
              "diameter": 18,
              "speedLoadIndex": "96H"
            }
          ]
        }
      }
    },
    "Polestar": {
      "RC 350 AWD": {},
      "RC-F": {},
      "RC-F Track Edition": {},
      "RCZ": {},
      "RCZ R": {},
      "RS Q3": {},
      "RS Q3 Performance": {},
      "RS Q3 Sportback": {},
      "RS Q8": {},
      "RS2": {},
      "RS3 Berline": {},
      "RS3 Limousine": {},
      "RS3 Sportback": {},
      "RS4": {},
      "RS4 Avant": {},
      "RS4 Cabrio": {},
      "RS5 Cabrio": {},
      "RS5 Quattro": {},
      "RS5 Sportback Quattro": {},
      "RS6": {},
      "RS6 Avant": {},
      "RS6 Avant Performance": {},
      "RS6 Avant Plus": {},
      "RS6 Plus": {},
      "RS7 Sportback": {},
      "RS7 Sportback Performance": {},
      "RX 200t": {},
      "RX 200t AWD": {},
      "RX 270": {},
      "RX 300": {},
      "RX 330": {},
      "RX 350": {},
      "RX 350 4WD": {},
      "RX 350 AWD": {},
      "RX 400h": {},
      "RX 450h": {},
      "RX 450h AWD": {},
      "RX 450hL AWD": {},
      "RX 7": {},
      "RX-8": {},
      "RZ Cabrio": {},
      "Racing": {},
      "Rainier": {},
      "Ramcharger AW 150": {},
      "Range Rover": {},
      "207 SW": {
        "2005-2010": {
          "Continental Test Variant 10": [
            {
              "fitmentLabel": "235/50 R18",
              "width": 235,
              "aspectRatio": 50,
              "diameter": 18,
              "speedLoadIndex": "105V"
            }
          ]
        }
      }
    },
    "Pontiac": {
      "Range Rover Evoque": {},
      "Range Rover Evoque (4X2)": {},
      "Range Rover Evoque AWD": {},
      "Range Rover Evoque Cabrio": {},
      "Range Rover Evoque Coup\u00e9": {},
      "Range Rover Evoque Coup\u00e9 (4X2)": {},
      "Range Rover HSE": {},
      "Range Rover II": {},
      "Range Rover III": {},
      "Range Rover IV": {},
      "Range Rover IV P400E": {},
      "Range Rover IV SV": {},
      "Range Rover SE": {},
      "Range Rover Sport": {},
      "Range Rover Sport HSE PHEV": {},
      "Range Rover Sport II": {},
      "Range Rover Sport II HST": {},
      "Range Rover Sport II P400E": {},
      "Range Rover Sport II SVR": {},
      "Range Rover Sport PHEV": {},
      "Range Rover Sport S PHEV": {},
      "Range Rover Sport SE": {},
      "Range Rover Sport SE PHEV": {},
      "Range Rover Velar": {},
      "Range Rover Velar SVAutobiography": {},
      "Ranger": {},
      "Ranger (2WD)": {},
      "Ranger 1800 LWB": {},
      "Ranger EV": {},
      "Ranger FX4": {},
      "Ranger I": {},
      "Ranger II": {},
      "Ranger III": {},
      "Ranger III 4x2": {},
      "Ranger III Raptor": {},
      "Rapid": {},
      "Rapid Spaceback": {},
      "Rapide": {},
      "Rapide AMR": {},
      "Rapide S": {},
      "Regera": {},
      "Rendezvous": {},
      "Rendezvous CXL": {},
      "Rendezvous CXL FWD": {},
      "Rendezvous FWD": {},
      "207 SW Outdoor": {
        "2011-2016": {
          "Continental Test Variant 11": [
            {
              "fitmentLabel": "235/50 R18",
              "width": 235,
              "aspectRatio": 50,
              "diameter": 18,
              "speedLoadIndex": "94V"
            }
          ]
        }
      }
    },
    "Porsche": {
      "Renegade": {},
      "Renegade 4X2": {},
      "Rexton": {},
      "Rexton 2WD": {},
      "Rexton 4WD": {},
      "Rezzo": {},
      "Rifter": {},
      "Rio": {},
      "Roadline": {},
      "Roadline GT": {},
      "Roadster": {},
      "Roadster (Z8)": {},
      "Roadster Brabus": {},
      "Roadster Coup\u00e9": {},
      "Roadster Coup\u00e9 Brabus": {},
      "Roadster MF4": {},
      "Roadster MF4-S": {},
      "Roadster MF5": {},
      "Roadster S (Z4)": {},
      "Roadster Sport": {},
      "Rocky": {},
      "Rodius": {},
      "Ronda": {},
      "Roomster": {},
      "Rover 75": {},
      "S 2000": {},
      "S 250 CDI": {},
      "S 280": {},
      "S 300": {},
      "S 300 Bluetec Hybrid": {},
      "S 300 TD": {},
      "S 320": {},
      "S 320 CDI": {},
      "S 320 CDI 4Matic": {},
      "S 350": {},
      "S 350 4Matic": {},
      "S 350 Bluetec": {},
      "S 350 Bluetec 4Matic": {},
      "S 350 Bluetec Hybrid": {},
      "S 350 CDI": {},
      "S 350 CDI 4Matic": {},
      "S 350 CDI BlueTec": {},
      "S 350 CDI BlueTec 4Matic": {},
      "S 350 D": {},
      "S 350 D 4Matic": {},
      "207 SW RC": {
        "2017-2021": {
          "Continental Test Variant 12": [
            {
              "fitmentLabel": "235/50 R18",
              "width": 235,
              "aspectRatio": 50,
              "diameter": 18,
              "speedLoadIndex": "98V"
            }
          ]
        }
      }
    },
    "Renault": {
      "S 400": {},
      "S 400 4Matic": {},
      "S 400 CDI": {},
      "S 400 D": {},
      "S 400 D 4Matic": {},
      "S 400 Hybrid": {},
      "S 420": {},
      "S 420 CDI": {},
      "S 430": {},
      "S 430 4Matic": {},
      "S 450": {},
      "S 450 4Matic": {},
      "S 450 4Matic Maybach": {},
      "S 450 Coup\u00e9 4Matic": {},
      "S 500": {},
      "S 500 4Matic": {},
      "S 500 Cabrio": {},
      "S 500 Coup\u00e9": {},
      "S 500 Coup\u00e9 4Matic": {},
      "S 500 L": {},
      "S 500 Maybach": {},
      "S 500 Plug-In Hybrid": {},
      "S 55": {},
      "S 560": {},
      "S 560 4 Matic": {},
      "S 560 4 Matic Coup\u00e9": {},
      "S 560 4 Matic Maybach": {},
      "S 560 Coup\u00e9": {},
      "S 560 Coup\u00e9 Cabrio": {},
      "S 560 E": {},
      "S 560 Maybach": {},
      "S 600": {},
      "S 600 Maybach": {},
      "S 63": {},
      "S 63 4MATIC Coupe": {},
      "S 63 4Matic": {},
      "S 63 4Matic Cabrio": {},
      "S 63 650 Cabrio": {},
      "S 63 Cabrio": {},
      "S 63 Coup\u00e9": {},
      "S 65": {},
      "S 65 Coup\u00e9": {},
      "S 65 Rocket 900 Coup\u00e9": {},
      "S 650 Maybach": {},
      "S V12 Biturbo": {},
      "208": {
        "2022-2026": {
          "Continental Test Variant 1": [
            {
              "fitmentLabel": "235/50 R19",
              "width": 235,
              "aspectRatio": 50,
              "diameter": 19,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      }
    },
    "Rolls Royce": {
      "S V12 Biturbo Cabrio": {},
      "S-Max": {},
      "S-Max AWD": {},
      "S-Type": {},
      "S-Type R": {},
      "S1": {},
      "S1 Sportback": {},
      "S2 Avant Quattro": {},
      "S2 Coup\u00e9": {},
      "S2 Quattro": {},
      "S3": {},
      "S3 Cabrio": {},
      "S3 Limousine": {},
      "S3 Sportback": {},
      "S4": {},
      "S4 Avant": {},
      "S4 Avant Quattro": {},
      "S4 Cabrio": {},
      "S4 Quattro": {},
      "S40": {},
      "S40 AWD": {},
      "S5": {},
      "S5 Cabrio": {},
      "S5 Coup\u00e9": {},
      "S5 Sportback": {},
      "S5 Sportback Quattro": {},
      "S6": {},
      "S6 Avant": {},
      "S60": {},
      "S60 AWD": {},
      "S60 Cross Country": {},
      "S60 Cross Country AWD": {},
      "S60 Polestar": {},
      "S60 R AWD": {},
      "S7 Comp\u00e9tition": {},
      "S7 Sportback": {},
      "S70": {},
      "S70 AWD": {},
      "S70 Bifuel": {},
      "S70 R": {},
      "S8 Plus Quattro": {},
      "S8 Quattro": {},
      "S80": {},
      "S80 AWD": {},
      "S80 Bifuel": {},
      "208 GT4": {
        "1998-2004": {
          "Continental Test Variant 2": [
            {
              "fitmentLabel": "235/50 R19",
              "width": 235,
              "aspectRatio": 50,
              "diameter": 19,
              "speedLoadIndex": "105V"
            }
          ]
        }
      }
    },
    "Rover": {
      "S90": {},
      "S90 AWD": {},
      "SC 430": {},
      "SL 280": {},
      "SL 300": {},
      "SL 320": {},
      "SL 350": {},
      "SL 400": {},
      "SL 500": {},
      "SL 55": {},
      "SL 55K8": {},
      "SL 600": {},
      "SL 63": {},
      "SL 65": {},
      "SL 73": {},
      "SLC 180": {},
      "SLC 200": {},
      "SLC 250 D": {},
      "SLC 300": {},
      "SLC 43": {},
      "SLK 200": {},
      "SLK 200 Kompressor": {},
      "SLK 230 Kompressor": {},
      "SLK 250": {},
      "SLK 250 CDI": {},
      "SLK 280": {},
      "SLK 300": {},
      "SLK 32": {},
      "SLK 320": {},
      "SLK 350": {},
      "SLK 55": {},
      "SLR": {},
      "SLS": {},
      "SLS Black Series": {},
      "SLS Elektrisch Drive": {},
      "SLS GT": {},
      "SLS GT Roadster": {},
      "SLS Roadster": {},
      "SQ2": {},
      "SQ5": {},
      "SQ5 Quattro Premium": {},
      "SQ5 Quattro Premium Plus": {},
      "SQ5 Quattro Prestige": {},
      "SQ5 Sportback Quattro": {},
      "SQ7": {},
      "208 GTB Turbo": {
        "2005-2010": {
          "Continental Test Variant 3": [
            {
              "fitmentLabel": "235/50 R19",
              "width": 235,
              "aspectRatio": 50,
              "diameter": 19,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      }
    },
    "Saab": {
      "SQ8 Quattro": {},
      "SRX": {},
      "ST1": {},
      "STS": {},
      "STS-V": {},
      "SVX": {},
      "SWACE": {},
      "SX4 (4X2)": {},
      "SX4 (4X4)": {},
      "SX4 S-Cross": {},
      "SX4 S-Cross AllGrip": {},
      "SZ Coup\u00e9": {},
      "Safrane": {},
      "Safrane Biturbo": {},
      "Safrane Quadra Baccara": {},
      "Sagaris": {},
      "Samurai": {},
      "Samurai Cabrio": {},
      "Sandero": {},
      "Sandero II": {},
      "Sandero II Stepway": {},
      "Sandero III": {},
      "Sandero III Stepway": {},
      "Sandero Stepway": {},
      "Santa Fe I 2WD": {},
      "Santa Fe I 4WD": {},
      "Santa Fe II 2WD": {},
      "Santa Fe II 4WD": {},
      "Santa Fe III 2WD": {},
      "Santa Fe III 4WD": {},
      "Santa Fe IV 2WD": {},
      "Santa Fe IV 4WD": {},
      "Santana SJ 410": {},
      "Santana SJ 413": {},
      "Saratoga": {},
      "Satellite HSV": {},
      "Satellite SVX": {},
      "Saxo": {},
      "Saxo Elektrisch": {},
      "Saxo VTR": {},
      "Saxo VTS": {},
      "Scala": {},
      "Scenic": {},
      "Scenic II": {},
      "Scenic III": {},
      "208 GTI": {
        "2011-2016": {
          "Continental Test Variant 4": [
            {
              "fitmentLabel": "235/50 R19",
              "width": 235,
              "aspectRatio": 50,
              "diameter": 19,
              "speedLoadIndex": "94V"
            }
          ]
        }
      }
    },
    "Santana": {
      "Scenic IV": {},
      "Scenic IV Hybrid Assist": {},
      "Scenic RX4": {},
      "Scenic Xmod": {},
      "Scenic Xmod (Extend Grip)": {},
      "Scirocco": {},
      "Scirocco GTS": {},
      "Scirocco R": {},
      "Scoupe": {},
      "Scudo": {},
      "Scudo Minibus": {},
      "Sebring": {},
      "Sebring Cabrio": {},
      "Sebring Coupe": {},
      "Sedici": {},
      "Sedici 4X4": {},
      "Seicento": {},
      "Senator B": {},
      "Senna": {},
      "Sephia": {},
      "Serena": {},
      "Seville": {},
      "Seville STS": {},
      "Shamal": {},
      "Sharan": {},
      "Sharan 4X4": {},
      "Sharan II": {},
      "Sharan II 4Motion": {},
      "Shuttle": {},
      "Sierra Cosworth 4x4": {},
      "Sierra Coup\u00e9": {},
      "Sierra Hatchback": {},
      "Sierra Kombi": {},
      "Sierra Kombi 4X4": {},
      "Sierra RS": {},
      "Sierra RS Cosworth": {},
      "Sierra XR4i": {},
      "Signum": {},
      "Silver Dawn": {},
      "Silver Seraph": {},
      "Silver Spirit": {},
      "Silver Spur": {},
      "Sintra": {},
      "Sirion": {},
      "Sirion 4WD": {},
      "208 GTI 30th": {
        "2017-2021": {
          "Continental Test Variant 5": [
            {
              "fitmentLabel": "235/50 R19",
              "width": 235,
              "aspectRatio": 50,
              "diameter": 19,
              "speedLoadIndex": "98V"
            }
          ]
        }
      }
    },
    "Seat": {
      "Sirion II": {},
      "Sirion II 4WD": {},
      "Sixty Sp\u00e9cial": {},
      "Slingshot Grand Touring LE": {},
      "Slingshot S": {},
      "Slingshot SL": {},
      "Slingshot SLR": {},
      "Sonata 10": {},
      "Sonata II": {},
      "Sonata III": {},
      "Sonata IV": {},
      "Sonata V": {},
      "Sorento": {},
      "Sorento 2WD": {},
      "Sorento 4WD": {},
      "Soul": {},
      "Soul II": {},
      "Soul II EV": {},
      "Sovereign": {},
      "Space Gear": {},
      "Space Runner": {},
      "Space Star": {},
      "Space Star II": {},
      "Space Wagon": {},
      "Space Wagon 4x4": {},
      "SpaceTourer": {},
      "Spark": {},
      "Speedster": {},
      "Speedster II": {},
      "Speedster Turbo": {},
      "Spider": {},
      "Splash": {},
      "Sport Ka": {},
      "Sportage I": {},
      "Sportage I 2WD": {},
      "Sportage II": {},
      "Sportage II 2WD": {},
      "Sportage III": {},
      "Sportage III 2WD": {},
      "Sportage IV": {},
      "Sportage IV 2WD": {},
      "Spring": {},
      "Sprinter 208 CDI 2t600": {},
      "Sprinter 208 CDI 2t800": {},
      "Sprinter 208 D 2t600": {},
      "208 GTS Turbo": {
        "2022-2026": {
          "Continental Test Variant 6": [
            {
              "fitmentLabel": "235/55 R18",
              "width": 235,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "91H"
            }
          ]
        }
      }
    },
    "Skoda": {
      "Sprinter 208 D 2t800": {},
      "Sprinter 210 D 2t600": {},
      "Sprinter 210 D 2t800": {},
      "Sprinter 211 CDI 2t600": {},
      "Sprinter 211 CDI 2t800": {},
      "Sprinter 212 CDI 2t600": {},
      "Sprinter 212 CDI 2t800": {},
      "Sprinter 213 CDI 2t600": {},
      "Sprinter 213 CDI 2t800": {},
      "Sprinter 216 CDI": {},
      "Sprinter 308 CDI 3t200": {},
      "Sprinter 308 CDI 3t500": {},
      "Sprinter 308 D 2t800": {},
      "Sprinter 308 D 3t500": {},
      "Sprinter 311 CDI 3t200": {},
      "Sprinter 311 CDI 3t500": {},
      "Sprinter 312 D 2t800": {},
      "Sprinter 312 D 3t500": {},
      "Sprinter 313 CDI 3t200": {},
      "Sprinter 313 CDI 3t5": {},
      "Sprinter 315 CDI 3t5": {},
      "Sprinter 316 CDI 3t200": {},
      "Sprinter 316 CDI 3t500": {},
      "Sprinter 408 CDI 3t500": {},
      "Sprinter 408 CDI 4t600": {},
      "Sprinter 408 D 3t500": {},
      "Sprinter 408 D 4t600": {},
      "Sprinter 411 CDI 3t500": {},
      "Sprinter 411 CDI 4t600": {},
      "Sprinter 412 D 3t500": {},
      "Sprinter 412 D 4t600": {},
      "Sprinter 413 CDI 3t500": {},
      "Sprinter 413 CDI 4t600": {},
      "Sprinter 416 CDI 3t500": {},
      "Sprinter 416 CDI 4t600": {},
      "Sprinter 616 CDI 5t990": {},
      "Sprinter II 209 CDI 3t": {},
      "Sprinter II 210 CDI 3t": {},
      "Sprinter II 211 CDI 3t": {},
      "Sprinter II 213 CDI 3t": {},
      "Sprinter II 215 CDI 3t": {},
      "Sprinter II 216 3t": {},
      "Sprinter II 216 CDI 3t": {},
      "Sprinter II 218 CDI 3t": {},
      "Sprinter II 219 CDI 3t": {},
      "208 II": {
        "1998-2004": {
          "Continental Test Variant 7": [
            {
              "fitmentLabel": "235/55 R18",
              "width": 235,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "94W"
            }
          ]
        }
      }
    },
    "Smart": {
      "Sprinter II 224 3t": {},
      "Sprinter II 309 CDI 3t5": {},
      "Sprinter II 310 CDI 3t5": {},
      "Sprinter II 311 CDI 3t5": {},
      "Sprinter II 311 CDI 4Matic 3t5": {},
      "Sprinter II 313 CDI 3t5": {},
      "Sprinter II 313 CDI 4Matic 3t5": {},
      "Sprinter II 315 CDI 4Matic 3t5": {},
      "Sprinter II 316 3t5": {},
      "Sprinter II 316 CDI 3t5": {},
      "Sprinter II 316 CDI 4Matic 3t5": {},
      "Sprinter II 316 NGT 3t5": {},
      "Sprinter II 318 CDI 3t5": {},
      "Sprinter II 318 CDI 4Matic 3t5": {},
      "Sprinter II 319 CDI 3t5": {},
      "Sprinter II 319 CDI 4Matic 3t5": {},
      "Sprinter II 324 3t5": {},
      "Sprinter II 413 CDI 4.6t": {},
      "Sprinter II 416 CDI 4.6t": {},
      "Sprinter II 419 CDI 4.6t": {},
      "Sprinter II 424 4.6t": {},
      "Sprinter II 509 CDI 5t": {},
      "Sprinter II 510 CDI 5t": {},
      "Sprinter II 511 CDI 5t": {},
      "Sprinter II 513 CDI 4Matic 5t": {},
      "Sprinter II 513 CDI 5t": {},
      "Sprinter II 515 CDI 5t": {},
      "Sprinter II 516 CDI 4Matic 5t": {},
      "Sprinter II 516 CDI 5t": {},
      "Sprinter II 516 NGT 5t": {},
      "Sprinter II 518 CDI 5t": {},
      "Sprinter II 519 CDI 4Matic 5t": {},
      "Sprinter II 519 CDI 5t": {},
      "Sprinter II 524 5t": {},
      "Sprinter III 211 CDI": {},
      "Sprinter III 211 CDI Tourer lang": {},
      "Sprinter III 214 CDI": {},
      "Sprinter III 214 CDI Tourer lang": {},
      "Sprinter III 214 CDI lang 4Matic": {},
      "Sprinter III 316 CDI": {},
      "Sprinter III 316 CDI lang": {},
      "Sprinter III 316 CDI lang 4Matic": {},
      "Sprinter III 319 CDI": {},
      "Sprinter III 319 CDI lang": {},
      "Sprinter III 319 CDI lang 4Matic": {},
      "213": {
        "2005-2010": {
          "Continental Test Variant 8": [
            {
              "fitmentLabel": "235/55 R18",
              "width": 235,
              "aspectRatio": 55,
              "diameter": 18,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      }
    },
    "Spyker": {
      "Spyder": {},
      "Spyker C8": {},
      "Starex": {},
      "Starex 4WD": {},
      "Starlet": {},
      "Stelvio": {},
      "Stelvio Q4": {},
      "Stelvio Sport": {},
      "Stelvio Sport AWD": {},
      "Stelvio Ti Sport AWD": {},
      "Stilo": {},
      "Stilo Sportwagon": {},
      "Stinger": {},
      "Stinger AWD": {},
      "Stonic": {},
      "Strada": {},
      "Stradale": {},
      "Stratus": {},
      "Stratus Cabrio": {},
      "Stream": {},
      "Street Ka": {},
      "Streetwise": {},
      "Sunfire": {},
      "Sunny": {},
      "Sunny Kombi": {},
      "Super 5": {},
      "Super 5 GTL": {},
      "Superb": {},
      "Superb 4x4": {},
      "Superb Combi": {},
      "Superb Combi 4x4": {},
      "Supra Cabrio": {},
      "Supra Coup\u00e9": {},
      "Swift": {},
      "Swift ALLGRIP": {},
      "Swift Cabrio": {},
      "Swift Sport": {},
      "S\u00e9rie B 4x2": {},
      "S\u00e9rie B 4x4": {},
      "T 180": {},
      "T 180 d": {},
      "T-Cross": {},
      "T-Roc": {},
      "T-Roc 4Motion": {},
      "T-Roc R": {},
      "214": {
        "2011-2016": {
          "Continental Test Variant 9": [
            {
              "fitmentLabel": "235/55 R19",
              "width": 235,
              "aspectRatio": 55,
              "diameter": 19,
              "speedLoadIndex": "105V"
            }
          ]
        }
      }
    },
    "Ssangyong": {
      "T350": {},
      "TGE": {},
      "TGE Erh\u00f6hte Nutzlast": {},
      "TGE einfache Pritsche": {},
      "TGE einfache Pritsche / Erh\u00f6hte Nutzlast": {},
      "TS1 GT": {},
      "TSR": {},
      "TSR-S": {},
      "TT": {},
      "TT Quattro": {},
      "TT RS": {},
      "TT RS Plus": {},
      "TT RS Plus Roadster": {},
      "TT RS Roadster": {},
      "TT Roadster": {},
      "TT Roadster Quattro": {},
      "TTS": {},
      "TTS Roadster": {},
      "Taigo": {},
      "Talento": {},
      "Talento Panomara": {},
      "Talisman": {},
      "Talisman Grandtour": {},
      "Tamora": {},
      "Taro": {},
      "Taro Extra": {},
      "Tarraco 4x2": {},
      "Tarraco 4x4": {},
      "Taycan": {},
      "Taycan 4S": {},
      "Taycan TURBO": {},
      "Taycan TURBO S": {},
      "Tempra": {},
      "Tempra Station Wagon": {},
      "Tempra Station Wagon 4X4": {},
      "Terios": {},
      "Terios 4WD": {},
      "Terios II": {},
      "Terios II 4WD": {},
      "Terracan": {},
      "Terrano": {},
      "Terrano II": {},
      "Terrano III": {},
      "Testarossa": {},
      "Thema": {},
      "214 Cabrio": {
        "2017-2021": {
          "Continental Test Variant 10": [
            {
              "fitmentLabel": "235/55 R19",
              "width": 235,
              "aspectRatio": 55,
              "diameter": 19,
              "speedLoadIndex": "91H"
            }
          ]
        }
      }
    },
    "Ssc": {
      "Thema 8.32": {},
      "Thema AWD": {},
      "Thema Station Wagon": {},
      "Thesis": {},
      "Thunderbird": {},
      "Tigra": {},
      "Tigra TwinTop": {},
      "Tiguan": {},
      "Tiguan 4motion": {},
      "Tiguan II": {},
      "Tiguan II 4motion": {},
      "Tiguan II Allspace": {},
      "Tiguan II Allspace 4motion": {},
      "Tiida": {},
      "Tipo": {},
      "Tipo II": {},
      "Tipo II Limousine": {},
      "Tipo II SW": {},
      "Tivoli": {},
      "Tivoli XLV 2WD": {},
      "Tivoli XLV 4WD": {},
      "Toledo": {},
      "Toledo GT": {},
      "Toledo II": {},
      "Toledo III": {},
      "Toledo IV": {},
      "Tonale": {},
      "Touareg": {},
      "Touareg II": {},
      "Touareg III": {},
      "Touran": {},
      "Touran II": {},
      "Touran III": {},
      "Tourneo Courier": {},
      "Tourneo Custom": {},
      "Town Car": {},
      "Townstar": {},
      "Trade": {},
      "Trafic II (Nutzlast:1000Kg)": {},
      "Trafic II (Nutzlast:1200Kg)": {},
      "Trafic III": {},
      "Trailblazer": {},
      "Trailblazer ACTIV": {},
      "Trailblazer EXT": {},
      "Trailblazer RS AWD": {},
      "214 GSI": {
        "2022-2026": {
          "Continental Test Variant 11": [
            {
              "fitmentLabel": "235/55 R19",
              "width": 235,
              "aspectRatio": 55,
              "diameter": 19,
              "speedLoadIndex": "94V"
            }
          ]
        }
      }
    },
    "Streetscooter": {
      "Trailblazer SS": {},
      "Trajet": {},
      "Trans Sport": {},
      "Trans Sport 4X4": {},
      "Trans-Sport": {},
      "Transit 2T": {},
      "Transit 2T 4X4": {},
      "Transit Connect": {},
      "Transit Connect II": {},
      "Transit Connect Titanium": {},
      "Transit Courier": {},
      "Transit Custom": {},
      "Transit Custom Kombi": {},
      "Transit FT 100 L": {},
      "Transit FT 100 S": {},
      "Transit FT 120": {},
      "Transit FT 130": {},
      "Transit FT 150 L": {},
      "Transit FT 150 S": {},
      "Transit FT 190 L": {},
      "Transit FT 230 S": {},
      "Transit FT 260": {},
      "Transit FT 280": {},
      "Transit FT 300 L": {},
      "Transit FT 300 M": {},
      "Transit FT 300 S": {},
      "Transit FT 330 L": {},
      "Transit FT 330 M": {},
      "Transit FT 330 S": {},
      "Transit FT 350 Doppelpritsche": {},
      "Transit FT 350 Kleintransporter": {},
      "Transit FT 350 einfache Pritsche": {},
      "Transit FT 80": {},
      "Transit Kleintransporter": {},
      "Transit Kleintransporter 4x4": {},
      "Transit Kombi": {},
      "Transporter (T5)": {},
      "Transporter (T6)": {},
      "Transporter 4Motion (T5)": {},
      "Transporter 4Motion (T6)": {},
      "Transporter kurz (T4)": {},
      "Transporter lang (T4)": {},
      "Traveller": {},
      "Trax": {},
      "Trax LS": {},
      "214 IS": {
        "1998-2004": {
          "Continental Test Variant 12": [
            {
              "fitmentLabel": "235/55 R19",
              "width": 235,
              "aspectRatio": 55,
              "diameter": 19,
              "speedLoadIndex": "94W"
            }
          ]
        }
      }
    },
    "Subaru": {
      "Trax LS AWD": {},
      "Trevis": {},
      "Trezia": {},
      "Tribeca": {},
      "Tribute": {},
      "Trooper": {},
      "Tucson I 2WD": {},
      "Tucson I 4WD": {},
      "Tucson II 2WD": {},
      "Tucson II 4WD": {},
      "Tucson III 2WD": {},
      "Tucson III 4WD": {},
      "Tucson IV 2WD": {},
      "Turbo": {},
      "Turbo R": {},
      "Turbo RL": {},
      "Tuscan": {},
      "Tuscan S": {},
      "Twingo": {},
      "Twingo II": {},
      "Twingo II RS": {},
      "Twingo II RS Gordini": {},
      "Twingo II RS Gordini ph2": {},
      "Twingo II RS ph2": {},
      "Twingo II ph2": {},
      "Twingo III": {},
      "Twingo III GT": {},
      "Twizy": {},
      "Twizy Cargo": {},
      "U 6 SUV": {},
      "UX200": {},
      "UX200 F Sport": {},
      "UX250h": {},
      "UX250h F Sport": {},
      "UX300e": {},
      "Ultimate 125": {},
      "Ultimate Aero": {},
      "Ultimate Aero TT": {},
      "Ultimate Aero XT": {},
      "Ulysse": {},
      "Uno": {},
      "Uno Turbo I.E": {},
      "Uno Van": {},
      "Urban Cruiser": {},
      "Urban Cruiser AWD": {},
      "214 ISL": {
        "2005-2010": {
          "Continental Test Variant 1": [
            {
              "fitmentLabel": "235/55 R19",
              "width": 235,
              "aspectRatio": 55,
              "diameter": 19,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      }
    },
    "Suzuki": {
      "Urus": {},
      "Urvan": {},
      "V 200": {},
      "V 200 CDI": {},
      "V 220 CDI": {},
      "V 220 CDI 4Matic": {},
      "V 220 D": {},
      "V 230": {},
      "V 250 BlueTec": {},
      "V 250 BlueTec 4Matic": {},
      "V 250 D": {},
      "V 280": {},
      "V 300 D": {},
      "V 350 D": {},
      "V12 Vanquish": {},
      "V12 Vanquish Carbon Edition": {},
      "V12 Vanquish Roadster": {},
      "V12 Vanquish S": {},
      "V12 Vantage": {},
      "V12 Vantage Roadster": {},
      "V12 Vantage S": {},
      "V12 Vantage S Roadster": {},
      "V12 Zagato": {},
      "V40": {},
      "V40 Cross Country": {},
      "V40 Cross Country AWD": {},
      "V50": {},
      "V50 AWD": {},
      "V60": {},
      "V60 AWD": {},
      "V60 Cross Country": {},
      "V60 Cross Country AWD": {},
      "V60 Plug-in Hybrid": {},
      "V60 Polestar": {},
      "V60 Polestar AWD": {},
      "V60 Twin Engine": {},
      "V70": {},
      "V70 AWD": {},
      "V70 Bifuel": {},
      "V70 Cross Country": {},
      "V70 R AWD": {},
      "V8": {},
      "V8 Vantage": {},
      "V8 Vantage N430": {},
      "V8 Vantage Roadster": {},
      "215 Cabrio": {
        "2011-2016": {
          "Continental Test Variant 2": [
            {
              "fitmentLabel": "235/60 R18",
              "width": 235,
              "aspectRatio": 60,
              "diameter": 18,
              "speedLoadIndex": "103Y"
            }
          ]
        }
      }
    },
    "Tesla": {
      "V8 Vantage Roadster S": {},
      "V8 Vantage S": {},
      "V90": {},
      "V90 AWD": {},
      "V90 Cross Country": {},
      "Valkyrie": {},
      "Vaneo": {},
      "Vanette": {},
      "Vanette C22": {},
      "Vanquish S": {},
      "Vanquish S Volante": {},
      "Vantage GT12": {},
      "Vantage V8": {},
      "Vario": {},
      "Vectra A": {},
      "Vectra A 2000": {},
      "Vectra A 4X4": {},
      "Vectra A GT": {},
      "Vectra B": {},
      "Vectra B Kombi": {},
      "Vectra B i500": {},
      "Vectra B i500 Caravan": {},
      "Vectra C": {},
      "Vectra C GTS": {},
      "Vectra C OPC": {},
      "Vectra C SW": {},
      "Vectra C SW OPC": {},
      "Vel Satis": {},
      "Veloster": {},
      "Venga": {},
      "Venom GT": {},
      "Venom GT Spyder": {},
      "Vento": {},
      "Verso": {},
      "Verso S": {},
      "Veyron 16.4": {},
      "Veyron 16.4 Grand Sport": {},
      "Veyron 16.4 Grand Sport Vitesse": {},
      "Veyron 16.4 Super Sport": {},
      "Viano": {},
      "Viano CDI": {},
      "Viano CDI 4Matic": {},
      "Viper GTS": {},
      "Viper GTS ACR": {},
      "Viper GTS-R": {},
      "216 Cabrio": {
        "2017-2021": {
          "Continental Test Variant 3": [
            {
              "fitmentLabel": "235/60 R18",
              "width": 235,
              "aspectRatio": 60,
              "diameter": 18,
              "speedLoadIndex": "91V"
            }
          ]
        }
      }
    },
    "Toyota": {
      "Viper RT/10": {},
      "Viper SRT 10": {},
      "Viper SRT 10 ACR": {},
      "Viper SRT ACR": {},
      "Virage": {},
      "Virage Volante": {},
      "Visa GTi": {},
      "Vision": {},
      "Vitara": {},
      "Vitara Allgrip": {},
      "Vitara Cabrio": {},
      "Vito 108 CDI": {},
      "Vito 108 D": {},
      "Vito 109 CDI": {},
      "Vito 110 CDI": {},
      "Vito 110 D": {},
      "Vito 111 CDI": {},
      "Vito 111 CDI 4X4": {},
      "Vito 112 CDI": {},
      "Vito 113": {},
      "Vito 113 CDI": {},
      "Vito 113 CDI 4X4": {},
      "Vito 114": {},
      "Vito 114 CDI": {},
      "Vito 114 CDI 4X4": {},
      "Vito 115 CDI": {},
      "Vito 115 CDI 4X4": {},
      "Vito 116 CDI": {},
      "Vito 116 CDI 4X4": {},
      "Vito 119": {},
      "Vito 119 CDI": {},
      "Vito 119 CDI 4x4": {},
      "Vito 120 CDI": {},
      "Vito 122": {},
      "Vito 122 CDI": {},
      "Vito 123": {},
      "Vito 126": {},
      "Vito Tourer 109 Bluetec": {},
      "Vito Tourer 111 Bluetec": {},
      "Vito Tourer 114 CDI": {},
      "Vito Tourer 114 CDI 4x4": {},
      "Vito Tourer 116 CDI": {},
      "Vito Tourer 116 CDI 4x4": {},
      "Vito Tourer 119 CDI": {},
      "Vito Tourer 119 CDI 4x4": {},
      "216 Coup\u00e9": {
        "2022-2026": {
          "Continental Test Variant 4": [
            {
              "fitmentLabel": "235/60 R18",
              "width": 235,
              "aspectRatio": 60,
              "diameter": 18,
              "speedLoadIndex": "96H"
            }
          ]
        }
      }
    },
    "Trabant": {
      "Vivaro II 2t700": {},
      "Vivaro II 2t900": {},
      "Vivaro III": {},
      "Volt": {},
      "Volt LT": {},
      "Voyager": {},
      "Voyager 4x4": {},
      "Wagon R+": {},
      "Wagon R+ 4X4": {},
      "Willys": {},
      "Wind": {},
      "Windstar": {},
      "Wraith": {},
      "Wrangler JK": {},
      "Wrangler JK 75th Anniversary Edition": {},
      "Wrangler JK Call of Duty Edition": {},
      "Wrangler JK Moab Edition": {},
      "Wrangler JK Rubicon": {},
      "Wrangler JK Rubicon X": {},
      "Wrangler JK Rubicon X 10th Anniversary": {},
      "Wrangler JK Sahara": {},
      "Wrangler JK Sport": {},
      "Wrangler JK Unlimited Sahara": {},
      "Wrangler JK Unlimited Sport": {},
      "Wrangler JL": {},
      "Wrangler JL Moab Edition": {},
      "Wrangler JL Sport": {},
      "Wrangler TJ": {},
      "Wrangler TJ 65th Anniversary Edition": {},
      "Wrangler TJ Rubicon": {},
      "Wrangler YJ": {},
      "X 1/9": {},
      "X 220 D 4X2": {},
      "X 220 D 4x4": {},
      "X 250 D 4X2": {},
      "X 250 D 4x4": {},
      "X 350 D 4x4": {},
      "X 90": {},
      "X-Bow": {},
      "X-Bow GT": {},
      "X-Bow R": {},
      "X-Trail": {},
      "X-Trail 4X2": {},
      "X-Trail 4x4": {},
      "X-Trail II": {},
      "216 GSI": {
        "1998-2004": {
          "Continental Test Variant 5": [
            {
              "fitmentLabel": "245/40 R19",
              "width": 245,
              "aspectRatio": 40,
              "diameter": 19,
              "speedLoadIndex": "105V"
            }
          ]
        }
      }
    },
    "Tvr": {
      "X-Trail III 4x2": {},
      "X-Trail III 4x4": {},
      "X-Type": {},
      "X-Type Estate": {},
      "XB7": {},
      "XC40": {},
      "XC40 AWD": {},
      "XC60": {},
      "XC60 AWD": {},
      "XC70 I": {},
      "XC70 II": {},
      "XC70 II 2WD": {},
      "XC90": {},
      "XC90 2WD": {},
      "XD3": {},
      "XD4": {},
      "XE": {},
      "XE AWD": {},
      "XE S": {},
      "XE SV Project 8": {},
      "XF": {},
      "XF (AWD)": {},
      "XF AWD": {},
      "XF R": {},
      "XF Sportbrake": {},
      "XF Sportbrake (AWD)": {},
      "XF Sportbrake AWD": {},
      "XFR-S": {},
      "XFR-S Sportbrake": {},
      "XG 25": {},
      "XG 350": {},
      "XJ": {},
      "XJ (AWD)": {},
      "XJ12": {},
      "XJ6": {},
      "XJ8": {},
      "XJL": {},
      "XJR": {},
      "XJR S": {},
      "XJS Cabrio": {},
      "XJS Coup\u00e9": {},
      "XK Cabrio": {},
      "XK Coup\u00e9": {},
      "XK8": {},
      "XK8 Cabrio": {},
      "216 GTI": {
        "2005-2010": {
          "Continental Test Variant 6": [
            {
              "fitmentLabel": "245/40 R19",
              "width": 245,
              "aspectRatio": 40,
              "diameter": 19,
              "speedLoadIndex": "92Y"
            }
          ]
        }
      }
    },
    "Volkswagen": {
      "XK8-R": {},
      "XK8-R Cabrio": {},
      "XKR": {},
      "XKR Cabrio": {},
      "XKR Coup\u00e9": {},
      "XKR-S Cabrio": {},
      "XKR-S Coup\u00e9": {},
      "XKR8": {},
      "XKR8 Coup\u00e9": {},
      "XL1": {},
      "XLR": {},
      "XLR-V": {},
      "XT4 350D AWD": {},
      "XT4 350D FWD": {},
      "XT4 350T AWD": {},
      "XT5": {},
      "XV": {},
      "Xantia": {},
      "Xantia Kombi": {},
      "Xceed": {},
      "Xedos 6": {},
      "Xedos 9": {},
      "Xm": {},
      "Xm Kombi": {},
      "Xsara": {},
      "Xsara Coup\u00e9": {},
      "Xsara Kombi": {},
      "Xsara Picasso": {},
      "Xsara VTS": {},
      "Y": {},
      "Y 10": {},
      "Y 10 4WD": {},
      "YRV": {},
      "YRV Turbo": {},
      "Yaris": {},
      "Yaris Cross": {},
      "Yaris GR Sport": {},
      "Yaris GRMN": {},
      "Yaris II": {},
      "Yaris II Sedan": {},
      "Yaris III": {},
      "Yaris III Hybrid": {},
      "Yaris IV": {},
      "Yaris IV Hybrid": {},
      "Yaris LE": {},
      "216 SI": {
        "2011-2016": {
          "Continental Test Variant 7": [
            {
              "fitmentLabel": "245/40 R19",
              "width": 245,
              "aspectRatio": 40,
              "diameter": 19,
              "speedLoadIndex": "96H"
            }
          ]
        }
      }
    },
    "Volvo": {
      "Yaris Verso": {},
      "Yaris XLE": {},
      "Yeti": {},
      "Yeti 4x4": {},
      "Ypsilon": {},
      "ZS": {},
      "Zafira A": {},
      "Zafira A OPC": {},
      "Zafira B": {},
      "Zafira B OPC": {},
      "Zafira C": {},
      "Zafira C Tourer": {},
      "Zafira Life": {},
      "Zeta": {},
      "Zoe": {},
      "Zonda C12": {},
      "Zonda Cinque": {},
      "Zonda Cinque Roadster": {},
      "Zonda F": {},
      "Zonda F Clubsport": {},
      "Zonda F Roadster": {},
      "Zonda R": {},
      "Zonda Revolucion": {},
      "Zonda Roadster": {},
      "Zonda S 7.3": {},
      "Zonda Tricolore": {},
      "Zx": {},
      "Zx Kombi": {},
      "Zx Kombi 4X4": {},
      "e": {},
      "e-2008 II": {},
      "e-208 II GT": {},
      "e-C4 III \u00e9lectrique": {},
      "e-Crafter Kleintransporter": {},
      "e-Niro": {},
      "e-Soul": {},
      "e-TRON Sportback Quattro Edition One": {},
      "e-Ulysse": {},
      "e-up!": {},
      "eTGE": {},
      "eTGE Erh\u00f6hte Nutzlast": {},
      "eVito": {},
      "eVito Tourer": {},
      "i-MiEV": {},
      "i10": {},
      "216 SLI": {
        "2017-2021": {
          "Continental Test Variant 8": [
            {
              "fitmentLabel": "245/40 R19",
              "width": 245,
              "aspectRatio": 40,
              "diameter": 19,
              "speedLoadIndex": "98Y"
            }
          ]
        }
      }
    },
    "Wiesmann": {
      "i20 I": {},
      "i20 II": {},
      "i20 II Coup\u00e9": {},
      "i20 III": {},
      "i3": {},
      "i30": {},
      "i30 CW": {},
      "i30 Fastback": {},
      "i30 Fastback N": {},
      "i30 N": {},
      "i30 SW": {},
      "i3s": {},
      "i4 M50 xDrive": {},
      "i4 eDrive40": {},
      "i40": {},
      "i40 SW": {},
      "i7": {},
      "i8": {},
      "i8 Roadster": {},
      "iOn": {},
      "ix iX xDrive 40": {},
      "ix iX xDrive 50": {},
      "ix3 iX3": {},
      "m2 M2": {},
      "m2 M2 Competition": {},
      "m3 M3": {},
      "m3 M3 CRT": {},
      "m3 M3 CS": {},
      "m3 M3 CSL": {},
      "m3 M3 Cabrio": {},
      "m3 M3 Coup\u00e9": {},
      "m3 M3 GT": {},
      "m3 M3 GTS": {},
      "m3 M3 SMG II": {},
      "m3 M3 SMG II Cabrio": {},
      "m3 M3 Sport Evolution": {},
      "m4 M4": {},
      "m4 M4 CS": {},
      "m4 M4 Cabrio": {},
      "m4 M4 Cabrio 30 Jahre": {},
      "m4 M4 GTS": {},
      "m5 M5": {},
      "m5 M5 - 30 Jahre": {},
      "m5 M5 Competion Package": {},
      "m5 M5 Competition": {},
      "218": {
        "2022-2026": {
          "Continental Test Variant 9": [
            {
              "fitmentLabel": "245/45 R19",
              "width": 245,
              "aspectRatio": 45,
              "diameter": 19,
              "speedLoadIndex": "91H"
            }
          ]
        }
      }
    },
    "Zenvo": {
      "m5 M5 Evolution": {},
      "m5 M5 Touring": {},
      "m6 M6 Cabrio": {},
      "m6 M6 Coup\u00e9": {},
      "m6 M6 Gran Coup\u00e9": {},
      "m8 M8 Cabrio": {},
      "m8 M8 Cabrio Competition": {},
      "m8 M8 Coup\u00e9": {},
      "m8 M8 Coup\u00e9 Competition": {},
      "m8 M8 Gran Coup\u00e9": {},
      "m8 M8 Gran Coup\u00e9 Comp\u00e9tition": {},
      "up!": {},
      "up! GTI": {},
      "x1 X1 sDrive16d": {},
      "x1 X1 sDrive18d": {},
      "x1 X1 sDrive18i": {},
      "x1 X1 sDrive20d": {},
      "x1 X1 sDrive20d EfficientDynamics": {},
      "x1 X1 sDrive20i": {},
      "x1 X1 xDrive18d": {},
      "x1 X1 xDrive20d": {},
      "x1 X1 xDrive20i": {},
      "x1 X1 xDrive23d": {},
      "x1 X1 xDrive23i": {},
      "x1 X1 xDrive25d": {},
      "x1 X1 xDrive25i": {},
      "x1 X1 xDrive28i": {},
      "x2 X2 M35i": {},
      "x2 X2 sDrive 20d": {},
      "x2 X2 sDrive16d": {},
      "x2 X2 sDrive18d": {},
      "x2 X2 sDrive18i": {},
      "x2 X2 sDrive20i": {},
      "x2 X2 xDrive18d": {},
      "x2 X2 xDrive20d": {},
      "x2 X2 xDrive20i": {},
      "x2 X2 xDrive25d": {},
      "x3 X3 2.0D": {},
      "x3 X3 2.5i": {},
      "x3 X3 3.0d": {},
      "x3 X3 3.0i": {},
      "x3 X3 M": {},
      "x3 X3 M Competition": {},
      "x3 X3 M40d": {},
      "x3 X3 M40i": {},
      "220": {
        "1998-2004": {
          "Continental Test Variant 10": [
            {
              "fitmentLabel": "245/45 R19",
              "width": 245,
              "aspectRatio": 45,
              "diameter": 19,
              "speedLoadIndex": "94V"
            }
          ]
        }
      }
    }
  },
  "source": "https://www.continental-tires.com/products/car/product-search/search-by-vehicle/",
  "capturedAt": "2026-08-10"
}
